whatwg/dom

dom.bs, dom.html
Move DOMSettableTokenList#value to DOMTokenList and remove the
DOMSettableTokenList interface.
Issue: #119
=> Fix #119: Merge DOMSettableTokenList into DOMTokenList

dom.bs, dom.html
See individual commits for details.
=> Updates to element creation and cross-references

dom.bs, dom.html
See https://github.com/whatwg/html/issues/1160 for context.
=> Rename scoped to composed and invert its meaning

dom.bs, dom.html
Fixes https://github.com/whatwg/html/issues/1359.
/cc @dominiccooney
=> Un-customify adopted elements

dom.bs, dom.html
=> Add relatedTarget to event dispatch

dom.bs, dom.html
=> Pass the old and new document to adoptedCallback

dom.bs, dom.html
=> Define nodeName as "#cdata-section" for CDATASection nodes

dom.bs, dom.html
This algorithm is impossible. Hopefully fixes #309.
=> Further Attr node fixes for compareDocumentPosition()

dom.bs, dom.html
=> Mark ATTRIBUTE_NODE and SHOW_ATTRIBUTE as no longer historical

dom.bs, dom.html
=> Make Element's slot attributes Unscopable

dom.bs, dom.html
Per discussion in https://github.com/whatwg/html/pull/1925.
=> Editorial: rename activation-behavior-related algorithms

dom.bs, dom.html
Needed for https://github.com/whatwg/html/issues/1959
=> Add a realm argument to "create an event"

dom.bs, dom.html
Fixes https://github.com/w3c/webcomponents/issues/571.
=> Stop re-signaling a slotchange event

dom.bs
Per suggestion in
https://github.com/whatwg/html/issues/1912#issuecomment-254900910.
=> Clarify isTrusted

.travis.yml
Based on
https://github.com/whatwg/fetch/commit/95b1de2c188d7e227e97d1adad8888676c72c116.
=> Meta: run output through the HTML checker

dom.bs
=> Pass listeners to inner invoke

dom.bs
See https://lists.w3.org/Archives/Public/www-dom/2017JanMar/0012.html.
=> Editorial: fix wording issue in "replace data"

dom.bs
Fixes #404.
Web platform test PR: w3c/web-platform-tests#4687
=> Fallback to legacy type only when event is trusted

dom.bs
See https://github.com/whatwg/infra/issues/22 for context.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/infra-return-continue/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/334428f...1904a05.html)
=> Editorial: use Infra's return and continue concepts

dom.bs
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/attribute-list-infra/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/3078a9d...53f20eb.html)
=> Editorial: define attribute list in terms of Infra's list

dom.bs
Closes #439.
***
[Preview](https://s3.amazonaws.com/pr-preview/johndai1984/dom/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/4ba35d9...johndai1984:864fc20.html)
=> Remove [CEReactions] on [PutForwards] readonly attributes

dom.bs
Fixes #495.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/return-traverse/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/cd3bcae...2f9435e.html)
=> Return the result of traversing

dom.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/ayg/dom/ocassion.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/77fe08c...ayg:0d222df.html)
=> Typo: ocassionally -> occasionally

dom.bs
Fixes #494.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/active-flag-exception/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/77fe08c...3372770.html)
=> Also unset the active flag when an exception is thrown

dom.bs
Needed for https://github.com/heycam/webidl/issues/365.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/idl-exposed/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/77fe08c...eb38c12.html)
=> Add [Exposed] to DOMTokenList

dom.bs
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/jakearchibald-patch-1/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/c3bbdb2...77c6bfa.html)
=> Example should check for current aborted state

README.md
Helps with https://github.com/whatwg/meta/issues/43.
=> Meta: use "good first issue" as label

dom.bs
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/code-unit-cleanup/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/56ca18c...2500ea5.html)
=> Editorial: use JavaScript string length

LICENSE, dom.bs
Also fixes a markup issue and linking error.
---
Do not merge until https://github.com/tabatkins/bikeshed/pull/1155 is merged.
***
<a href="https://whatpr.org/dom/553.html" title="Last updated on Jan 5, 2018, 3:18 PM GMT (aaa4c6a)">Preview</a> | <a href="https://whatpr.org/dom/553/5222eee...aaa4c6a.html" title="Last updated on Jan 5, 2018, 3:18 PM GMT (aaa4c6a)">Diff</a>
=> Meta: use new WHATWG boilerplate and license

README.md
Addresses:
- https://github.com/whatwg/meta/issues/65
=> Editorial: Link to whatwg/meta COMMITING.md

.travis.yml, CONTRIBUTING.md, README.md
Helps with https://github.com/whatwg/meta/issues/65.
=> Meta: define merge policy and add CONTRIBUTING.md

dom.bs
***
<a href="https://whatpr.org/dom/588.html" title="Last updated on Mar 11, 2018, 4:12 PM GMT (826bc86)">Preview</a> | <a href="https://whatpr.org/dom/588/3f2620f...826bc86.html" title="Last updated on Mar 11, 2018, 4:12 PM GMT (826bc86)">Diff</a>
=> Editorial: link to HTTPS version of the Live DOM Viewer

dom.bs
It's better to talk about its root and then go through the (inclusive) descendants.
Fixes #526.
***
<a href="https://whatpr.org/dom/599.html" title="Last updated on Mar 15, 2018, 7:18 AM GMT (4a233ae)">Preview</a> | <a href="https://whatpr.org/dom/599/2bdabb1...4a233ae.html" title="Last updated on Mar 15, 2018, 7:18 AM GMT (4a233ae)">Diff</a>
=> A node doesn't have an associated tree

dom.bs
And perform some minor cleanup elsewhere.
Fixes #394.
***
<a href="https://whatpr.org/dom/592.html" title="Last updated on Mar 16, 2018, 8:44 AM GMT (7ac9928)">Preview</a> | <a href="https://whatpr.org/dom/592/5f4249f...7ac9928.html" title="Last updated on Mar 16, 2018, 8:44 AM GMT (7ac9928)">Diff</a>
=> Remove additions from the historical section

dom.bs
***
<a href="https://whatpr.org/dom/605.html" title="Last updated on Mar 16, 2018, 10:13 AM GMT (3e5cd1b)">Preview</a> | <a href="https://whatpr.org/dom/605/5f4249f...3e5cd1b.html" title="Last updated on Mar 16, 2018, 10:13 AM GMT (3e5cd1b)">Diff</a>
=> Editorial: be more consistent with callbacks

dom.bs
Fixes the parts of #87 I understand.
***
<a href="https://whatpr.org/dom/594.html" title="Last updated on Mar 13, 2018, 10:20 AM GMT (acae239)">Preview</a> | <a href="https://whatpr.org/dom/594/87e028a...acae239.html" title="Last updated on Mar 13, 2018, 10:20 AM GMT (acae239)">Diff</a>
=> Editorial: fix several issues with traversal

dom.bs
See https://github.com/whatwg/dom/pull/603#pullrequestreview-104750860.
***
<a href="https://whatpr.org/dom/610.html" title="Last updated on Mar 17, 2018, 5:59 AM GMT (e994a0c)">Preview</a> | <a href="https://whatpr.org/dom/610/a6d17ae...e994a0c.html" title="Last updated on Mar 17, 2018, 5:59 AM GMT (e994a0c)">Diff</a>
=> Editorial: grammar fix

dom.bs
Fixes #618 (make sure to amend the commit message when landing to mention this)
=> Editorial: remove object argument from inner invoke

dom.bs
***
<a href="https://whatpr.org/dom/622.html" title="Last updated on Mar 28, 2018, 1:38 PM GMT (659d49d)">Preview</a> | <a href="https://whatpr.org/dom/622/fc16564...659d49d.html" title="Last updated on Mar 28, 2018, 1:38 PM GMT (659d49d)">Diff</a>
=> Editorial: address cross-reference issues with ranges

dom.bs
For:
* id/className/classList/slot
***
<a href="https://whatpr.org/dom/601.html" title="Last updated on Apr 9, 2018, 12:52 PM GMT (c315793)">Preview</a> | <a href="https://whatpr.org/dom/601/7a7f7f3...c315793.html" title="Last updated on Apr 9, 2018, 12:52 PM GMT (c315793)">Diff</a>
=> Add more domintro boxes

dom.bs
Fixes #496.
***
<a href="https://whatpr.org/dom/615.html" title="Last updated on Mar 23, 2018, 12:55 PM GMT (d6d929d)">Preview</a> | <a href="https://whatpr.org/dom/615/5be84cc...d6d929d.html" title="Last updated on Mar 23, 2018, 12:55 PM GMT (d6d929d)">Diff</a>
=> NodeIterator's pre-removing steps need to account for node being root

dom.bs
***
<a href="https://whatpr.org/dom/634.html" title="Last updated on Apr 21, 2018, 3:58 AM GMT (7e18eca)">Preview</a> | <a href="https://whatpr.org/dom/634/618e1f2...7e18eca.html" title="Last updated on Apr 21, 2018, 3:58 AM GMT (7e18eca)">Diff</a>
=> Meta: fix service worker reference

dom.bs
***
<a href="https://whatpr.org/dom/631.html" title="Last updated on Apr 10, 2018, 9:34 AM GMT (550a1cd)">Preview</a> | <a href="https://whatpr.org/dom/631/c80e017...550a1cd.html" title="Last updated on Apr 10, 2018, 9:34 AM GMT (550a1cd)">Diff</a>
=> Editorial: make traverser object associations more explicit

dom.bs
See https://github.com/whatwg/dom/issues/461 for details.
***
<a href="https://whatpr.org/dom/656.html" title="Last updated on Jun 21, 2018, 8:40 AM GMT (1a12e27)">Preview</a> | <a href="https://whatpr.org/dom/656/c69d7c0...1a12e27.html" title="Last updated on Jun 21, 2018, 8:40 AM GMT (1a12e27)">Diff</a>
=> Add toggleAttribute to Element.

dom.bs
Fixes #691.
***
<a href="https://whatpr.org/dom/692.html" title="Last updated on Sep 11, 2018, 3:32 PM GMT (effb3b6)">Preview</a> | <a href="https://whatpr.org/dom/692/28cdb47...effb3b6.html" title="Last updated on Sep 11, 2018, 3:32 PM GMT (effb3b6)">Diff</a>
=> Editorial: a removed node's root is itself

dom.bs
Fixes #645.
***
<a href="https://whatpr.org/dom/753.html" title="Last updated on May 17, 2019, 10:06 AM UTC (d229069)">Preview</a> | <a href="https://whatpr.org/dom/753/98564fc...d229069.html" title="Last updated on May 17, 2019, 10:06 AM UTC (d229069)">Diff</a>
=> Editorial: rename event path's item and target

dom.bs
***
<a href="https://whatpr.org/dom/785.html" title="Last updated on Sep 23, 2019, 10:09 AM UTC (07a9172)">Preview</a> | <a href="https://whatpr.org/dom/785/dea5d92...07a9172.html" title="Last updated on Sep 23, 2019, 10:09 AM UTC (07a9172)">Diff</a>
=> Add onabort definition and add onslotchange

dom.bs
***
<a href="https://whatpr.org/dom/681.html" title="Last updated on Nov 4, 2019, 9:22 AM UTC (5f7b4c4)">Preview</a> | <a href="https://whatpr.org/dom/681/7a48d64...5f7b4c4.html" title="Last updated on Nov 4, 2019, 9:22 AM UTC (5f7b4c4)">Diff</a>
=> Editorial: add missing coma in attachShadow

dom.bs
See https://github.com/whatwg/dom/issues/787#issuecomment-550485387 onward for analysis and test references.
Fixes #787.
@pwombwell care to review? I'll land it next week I suppose if all is in order.
***
<a href="https://whatpr.org/dom/794.html" title="Last updated on Nov 8, 2019, 2:21 PM UTC (e2b172b)">Preview</a> | <a href="https://whatpr.org/dom/794/b9383a3...e2b172b.html" title="Last updated on Nov 8, 2019, 2:21 PM UTC (e2b172b)">Diff</a>
=> Address infinite loop in TreeWalker's nextNode()

dom.bs
***
<a href="https://whatpr.org/dom/795.html" title="Last updated on Nov 13, 2019, 2:43 AM UTC (3a1bdd1)">Preview</a> | <a href="https://whatpr.org/dom/795/868f173...3a1bdd1.html" title="Last updated on Nov 13, 2019, 2:43 AM UTC (3a1bdd1)">Diff</a>
=> Editorial: punctuation and capitalization fixes

dom.bs
***
<a href="https://whatpr.org/dom/803.html" title="Last updated on Dec 6, 2019, 11:55 AM UTC (dbe4033)">Preview</a> | <a href="https://whatpr.org/dom/803/ce4c6ba...dbe4033.html" title="Last updated on Dec 6, 2019, 11:55 AM UTC (dbe4033)">Diff</a>
=> Editorial: modernize formatting (mainly Mutation algorithms)

dom.bs
Helps with #801. Closes #802.
***
<a href="https://whatpr.org/dom/804.html" title="Last updated on Dec 6, 2019, 12:52 PM UTC (1c2b689)">Preview</a> | <a href="https://whatpr.org/dom/804/1401218...1c2b689.html" title="Last updated on Dec 6, 2019, 12:52 PM UTC (1c2b689)">Diff</a>
=> Editorial: remove parent argument to remove

dom.bs
Fixes #811.
***
<a href="https://whatpr.org/dom/821.html" title="Last updated on Jan 13, 2020, 11:54 PM UTC (2ab3901)">Preview</a> | <a href="https://whatpr.org/dom/821/55379a7...2ab3901.html" title="Last updated on Jan 13, 2020, 11:54 PM UTC (2ab3901)">Diff</a>
=> Editorial: mark initCustomEvent and createEvent as // historical

dom.bs
See https://github.com/whatwg/infra/pull/292.
(This needs to wait at least a day until after that PR is merged as otherwise the cross-references might go faulty.)
cc @andreubotella
***
<a href="https://whatpr.org/dom/843.html" title="Last updated on Mar 9, 2020, 11:41 AM UTC (e0e938c)">Preview</a> | <a href="https://whatpr.org/dom/843/b4e91f5...e0e938c.html" title="Last updated on Mar 9, 2020, 11:41 AM UTC (e0e938c)">Diff</a>
=> Editorial: align with Infra string changes

dom.bs
Fixes #738.
***
<a href="https://whatpr.org/dom/876.html" title="Last updated on Jun 28, 2020, 8:59 AM UTC (8c7db33)">Preview</a> | <a href="https://whatpr.org/dom/876/ad06a4c...8c7db33.html" title="Last updated on Jun 28, 2020, 8:59 AM UTC (8c7db33)">Diff</a>
=> Editorial: pass invocationTargetInShadowTree to "inner invoke"

dom.bs
***
<a href="https://whatpr.org/dom/887.html" title="Last updated on Aug 25, 2020, 2:52 PM UTC (f68ea89)">Preview</a> | <a href="https://whatpr.org/dom/887/b80c4f9...f68ea89.html" title="Last updated on Aug 25, 2020, 2:52 PM UTC (f68ea89)">Diff</a>
=> Editorial: use Infra language for Aborting section

dom.bs
***
<a href="https://whatpr.org/dom/897.html" title="Last updated on Sep 29, 2020, 2:58 PM UTC (3bbe5d4)">Preview</a> | <a href="https://whatpr.org/dom/897/f837ce1...3bbe5d4.html" title="Last updated on Sep 29, 2020, 2:58 PM UTC (3bbe5d4)">Diff</a>
=> Meta: link Review Draft

dom.bs
***
<a href="https://whatpr.org/dom/898.html" title="Last updated on Sep 30, 2020, 1:30 PM UTC (0660235)">Preview</a> | <a href="https://whatpr.org/dom/898/03d45d1...0660235.html" title="Last updated on Sep 30, 2020, 1:30 PM UTC (0660235)">Diff</a>
=> Meta: put custom element acknowledgment in the IPR section

dom.bs
@JasonTheKitten please take a look.
***
<a href="https://whatpr.org/dom/909.html" title="Last updated on Oct 27, 2020, 9:35 AM UTC (48c1a69)">Preview</a> | <a href="https://whatpr.org/dom/909/8c0049e...48c1a69.html" title="Last updated on Oct 27, 2020, 9:35 AM UTC (48c1a69)">Diff</a>
=> Editorial: rephrase initEvent() note

dom.bs
***
<a href="https://whatpr.org/dom/971.html" title="Last updated on Apr 16, 2021, 6:50 AM UTC (b12ff75)">Preview</a> | <a href="https://whatpr.org/dom/971/0d2dc63...b12ff75.html" title="Last updated on Apr 16, 2021, 6:50 AM UTC (b12ff75)">Diff</a>
=> Meta: remove redundant quotes

dom.bs
***
<a href="https://whatpr.org/dom/970.html" title="Last updated on Apr 16, 2021, 6:40 AM UTC (814a2d1)">Preview</a> | <a href="https://whatpr.org/dom/970/0d2dc63...814a2d1.html" title="Last updated on Apr 16, 2021, 6:40 AM UTC (814a2d1)">Diff</a>
=> Editorial: use modern dictionary syntax

dom.bs
***
<a href="https://whatpr.org/dom/994.html" title="Last updated on Jun 25, 2021, 9:31 AM UTC (e2848d2)">Preview</a> | <a href="https://whatpr.org/dom/994/f18cef9...e2848d2.html" title="Last updated on Jun 25, 2021, 9:31 AM UTC (e2848d2)">Diff</a>
=> addEventListener: signal in flattening more output

dom.bs
Closes #1036.
***
<a href="https://whatpr.org/dom/1037.html" title="Last updated on Nov 29, 2021, 4:05 PM UTC (69a8beb)">Preview</a> | <a href="https://whatpr.org/dom/1037/4ca187f...69a8beb.html" title="Last updated on Nov 29, 2021, 4:05 PM UTC (69a8beb)">Diff</a>
=> Editorial: update some links

dom.bs
Closes #1013.
***
<a href="https://whatpr.org/dom/1058.html" title="Last updated on Feb 15, 2022, 9:29 AM UTC (cc3d6bf)">Preview</a> | <a href="https://whatpr.org/dom/1058/dbb7916...cc3d6bf.html" title="Last updated on Feb 15, 2022, 9:29 AM UTC (cc3d6bf)">Diff</a>
=> Add Security and privacy considerations section

dom.bs
***
<a href="https://whatpr.org/dom/1121.html" title="Last updated on Oct 17, 2022, 9:57 AM UTC (7dfb6f6)">Preview</a> | <a href="https://whatpr.org/dom/1121/c3ca964...7dfb6f6.html" title="Last updated on Oct 17, 2022, 9:57 AM UTC (7dfb6f6)">Diff</a>
=> Editorial: align with realm lowercasing

dom.bs
***
<a href="https://whatpr.org/dom/1122.html" title="Last updated on Oct 26, 2022, 12:20 PM UTC (c731f1e)">Preview</a> | <a href="https://whatpr.org/dom/1122/bf5f6c2...c731f1e.html" title="Last updated on Oct 26, 2022, 12:20 PM UTC (c731f1e)">Diff</a>
=> Meta: my employer changed

dom.bs
Fixes part of #1130.
***
<a href="https://whatpr.org/dom/1131.html" title="Last updated on Nov 24, 2022, 4:43 PM UTC (e6b4e0c)">Preview</a> | <a href="https://whatpr.org/dom/1131/6b3f055...e6b4e0c.html" title="Last updated on Nov 24, 2022, 4:43 PM UTC (e6b4e0c)">Diff</a>
=> Meta: correct createContextualFragment() link

dom.bs
***
<a href="https://whatpr.org/dom/1143.html" title="Last updated on Jan 16, 2023, 10:47 AM UTC (cb85020)">Preview</a> | <a href="https://whatpr.org/dom/1143/4a6af79...cb85020.html" title="Last updated on Jan 16, 2023, 10:47 AM UTC (cb85020)">Diff</a>
=> Meta: address xref issues

dom.bs
Stop exporting it as per discussion in https://github.com/whatwg/html/pull/8575.
cc @dontcallmedom
***
<a href="https://whatpr.org/dom/1166.html" title="Last updated on Feb 22, 2023, 3:44 PM UTC (a288369)">Preview</a> | <a href="https://whatpr.org/dom/1166/d34d52d...a288369.html" title="Last updated on Feb 22, 2023, 3:44 PM UTC (a288369)">Diff</a>
=> Editorial: minor reflect cleanup

dom.bs
Also always include for=tree for descendants.
***
<a href="https://whatpr.org/dom/1173.html" title="Last updated on Mar 22, 2023, 12:18 PM UTC (e63f4d1)">Preview</a> | <a href="https://whatpr.org/dom/1173/4db09dd...e63f4d1.html" title="Last updated on Mar 22, 2023, 12:18 PM UTC (e63f4d1)">Diff</a>
=> Editorial: an HTMLCollection

dom.bs
Sorry @annevk, one more export needed.
Context: https://github.com/w3c/ServiceWorker/pull/1674/files#diff-7bdebf23eab87aaf2676a41586076394031b6b98fde24e35d1672aa65a1cc0feR3010
***
<a href="https://whatpr.org/dom/1174.html" title="Last updated on Mar 22, 2023, 3:59 PM UTC (031e997)">Preview</a> | <a href="https://whatpr.org/dom/1174/79f58b7...031e997.html" title="Last updated on Mar 22, 2023, 3:59 PM UTC (031e997)">Diff</a>
=> Export event listener callback

dom.bs
***
<a href="https://whatpr.org/dom/1210.html" title="Last updated on Jun 16, 2023, 1:15 PM UTC (d62aa8e)">Preview</a> | <a href="https://whatpr.org/dom/1210/ab2738b...d62aa8e.html" title="Last updated on Jun 16, 2023, 1:15 PM UTC (d62aa8e)">Diff</a>
=> Editorial: always pass oldParent to removing steps

README.md
Add the additional formatting rules that originated in Fetch.
=> Meta: update repository files

review-drafts/2024-06.bs
The [June 2024 Review Draft](https://dom.spec.whatwg.org/review-drafts/2024-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/dom/1292.html" title="Last updated on Jun 17, 2024, 11:18 AM UTC (e09d65d)">Preview</a> | <a href="https://whatpr.org/dom/1292/0616094...e09d65d.html" title="Last updated on Jun 17, 2024, 11:18 AM UTC (e09d65d)">Diff</a>
=> Review Draft Publication: June 2024

.github/workflows/build.yml, PULL_REQUEST_TEMPLATE.md, dom.bs
Also pull in some recent whatwg/spec-factory changes while here.
Closes #1309.
***
<a href="https://whatpr.org/dom/1312.html" title="Last updated on Sep 20, 2024, 3:14 PM UTC (a98d125)">Preview</a> | <a href="https://whatpr.org/dom/1312/484c8bc...a98d125.html" title="Last updated on Sep 20, 2024, 3:14 PM UTC (a98d125)">Diff</a>
=> Meta: link Simplified Chinese translation

dom.bs
* WebKit (already implemented)
* Chromium (already implemented)
* https://github.com/web-platform-tests/wpt/pull/53323
* Chromium: N/A
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1972445
* WebKit: N/A
***
<a href="https://whatpr.org/dom/1384.html" title="Last updated on Jun 24, 2025, 9:12 AM UTC (e69f764)">Preview</a> | <a href="https://whatpr.org/dom/1384/12407f8...e69f764.html" title="Last updated on Jun 24, 2025, 9:12 AM UTC (e69f764)">Diff</a>
=> Copy document's allow declarative shadow roots
