dom.bs, dom.html
/node/ will never be null when reaching the head of these loops, unless it is
null when starting the outer loop.  This should somewhat clarify how the loop
actually runs.
=> Remove unnecessary conditions from the 'traverse children' algorithm.

dom.bs, dom.html
@Ms2ger pointed out to me that the fix introduced in #66 is less than perfect, because the unsuspecting loop over node's inclusive descendants mean running their adopting steps in a tree of which nodes are owned by two different documents.
=> Make two loops to adopt a node

dom.bs, dom.html
This is a stab at adding the required hook in DOM so that `iframe@sandbox`, `link@rel` and hopefully future features would be able to use `DOMTokenList.add()` for feature detection.
Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29061
/cc @annevk @domenic @zcorpan @Ms2ger
=> DOMTokenList hook to validate added token is in a supported set of keywords

dom.bs, dom.html
Closes https://github.com/whatwg/dom/issues/106
@annevk - I added a validation step to the DOMTokenList creation. Can you take a look?
=> Add a validation step when a new DOMTokenList is created

dom.bs, dom.html
If the replacing node is the replaced child, the node doesn't need and
shouldn't be adopted into the parent's document because it removes it from
the parent, which is already done in the very next step.
The adoption step is made conditional and not the removing one to not
artificially increase the number of mutation records being queued during
the replacing as a whole.
=> Do not remove child from its parent when replacing a node by itself

dom.bs, dom.html
Only one mutation record should be queued, according to both WebKit and Gecko.
=> Fix the set an attribute algorithm

dom.bs, dom.html
See http://logs.glob.uno/?c=freenode%23whatwg&s=14+Mar+2016&e=14+Mar+2016#c988870 for confusion. In particular:
> yeah probably a confusion because of "clone" ; a "clone" operation that does not return the same object type... hmmm...
Also see https://github.com/tabatkins/bikeshed/issues/630 for the bogus change to UIEvents in the generated references.
Ack @therealglazou
=> Editorial: clone a range → clone the contents of a range

dom.bs, dom.html
Upstreaming from https://rawgit.com/w3c/webcomponents/15a203c8393aef0df7223ab1d43406aa11a7e71e/spec/custom/index.html.
I envision this being done in three stages:
- DOM pull request (i.e. this pull request), which references the above URL for certain concepts
- HTML pull request, which references DOM for certain concepts
- A small DOM pull request, which changes the links to point to HTML instead of the above URL.
Given that we'd like to land this soon, but our timezones are not always super-overlapping, feel free to tweak and merge while I'm asleep, or even just push fixup commits to this branch for me to review. That is, I'd rather we both do the work on this branch, and get this merged in sooner, instead of the traditional submitter-reviewer back and forth.
=> Upstream Custom Elements

dom.bs, dom.html
As pointed out by zcorpan in #227.
=> SVGEvent is only Gecko, Blink also has SVGEvents

dom.bs, dom.html
Browsers typically disable touch events on non-touch devices, and
there exists Web content that detects this difference using
createEvent.
----
Also see https://github.com/w3c/touch-events/issues/64 for a possible spec hook for this.
I'm not sure about the wording, happy to tweak it.
I updated bikeshed and got some unrelated differences in the output, FYI.
=> Fix #227: Make createEvent("touchevent") sometimes throw

dom.bs, dom.html
Fixes https://github.com/w3c/webcomponents/issues/288.
This defines the slotchange event in response to remove/insert
operations, changes to a slot’s name attribute, and changes to an
element’s slot attribute.
This also introduces the assigned nodes concept for slots, and assigned
slot concept for slotables.
Slotables now also have a name, rather than a “get name”.
The slotchange event dispatches just after mutation observers.
=> Shadow: define slotchange event

dom.bs, dom.html
Includes support for scoped events that a number of HTML features
require. The invocation order handles CAPTURE first, then TARGET and
BUBBLE. Retargeting happens during the BUBBLE phase as developers
mostly use BUBBLE listeners and therefore it would be unexpected if
it was interleaved with the CAPTURE phase.
A split approach where capture listeners for the targets are invoked
during CAPTURE and bubble listeners are invoked during BUBBLE was
also considered, but eventually dismissed as it would make shadow
hosts observable.
Fixes #237 and fixes https://github.com/w3c/webcomponents/issues/485.
=> Shadow: define event retargeting for shadow trees

dom.bs, dom.html
Fixes #242. Also reverts
https://github.com/w3c/webcomponents/issues/432 as it appears to no
longer be needed. If we ever have an event path that starts with a
non-node and ends with a node we'll have to add that complexity back.
(The reason it is named composedPath() is because deepPath() and
various other names were no longer viable after Chrome's initial
experiment. See the various issues.)
=> Shadow: define composedPath()

dom.bs, dom.html
Change node.baseURI, document.URL, document.documentURI and
document.origin to use USVString.
----
Note: genned with updated bikeshed
=> Use USVString for URLs and origins in IDL

dom.bs, dom.html
As of https://github.com/whatwg/html/pull/1309, this is no longer necessary, as it is taken care of in the Construct(C) step.
Ideally don't merge this until that PR is merged.
=> Don't set custom element state redundantly

dom.bs, dom.html
Part of fixing https://github.com/whatwg/html/issues/1298 and https://github.com/whatwg/html/issues/1360.
=> Save the is="" value an element was created with

dom.bs, dom.html
https://github.com/whatwg/html/issues/1297 led to a series of changes
which cause the custom element state to be set to "defined" by the
HTMLElement constructor. This invalidates the super()-then-throw
example. We instead replace it with an example that fails to call
super().
Fixes https://github.com/whatwg/html/issues/1396.
--
Thanks @kojiishi for reporting.
Not sure why so much Bikeshed churn, but whatevs...
=> Fix example of "undefined" custom element state

dom.bs, dom.html
Fixes #241. Unfortunately a variety of good short names is incompatible
with the web.
Furthermore, the argument was made that a method better exposes the
fact that this is not always a O(1) operation and can be used to return
the shadow-including root when given an argument.
=> Rename rootNode to getRootNode() and add composed argument

README.md
This will ensure contributors are always using the latest up-to-date Bikeshed.
=> Meta: add advice on using the Bikeshed HTTP API

dom.bs, dom.html
Now we have “in a document tree” and “is connected” instead. Fixes part
of #238.
=> Rename "in a (shadow-including) document"

dom.bs, dom.html
This is part of implementing the consensus arrived at in https://github.com/w3c/webcomponents/issues/512. Now each custom element carries with it a custom element definition. Adoption now enqueues an adoptedCallback call.
=> Set the stage for new custom element adoption semantics

dom.bs, dom.html
Fix #286. Add the minimum hook to an event dispatch so other
specifications, such as TouchEvents spec, can retarget the event's
attributes, before invoking an event.
=> Shadow: Add "retargeting steps" to the dispatch algorithm

dom.bs, dom.html
This means in particular that they will not match :defined. Fixes https://github.com/w3c/webcomponents/issues/540.
=> Mark more elements in browsing-context-less documents as "undefined"

dom.bs, dom.html
I’m thirty now so it’s time to face reality. This fixes
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27386. This also closes
#190 by deciding to not enumerate subclasses of concrete (non-abstract)
interfaces (ShadowRoot and CDATASection in particular).
=> Reinstate CDATASection

dom.bs, dom.html
Now we use "closed-shadow-hidden" instead. Fixes #285.
=> Shadow: Rename "unclosed node"

dom.bs, dom.html
Unfortunately AttrExodus never quite became the success we all wished
it would be and the benefits with Attr no longer taking children (yay)
are rather marginal anyway.
The biggest change is to the compareDocumentPosition() algorithm. Other
noteworthy changes are that all attribute creation now needs to set a
node document.
Fixes #102.
=> Make Attr inherit from Node again

dom.bs, dom.html
Such exceptions can occur due to custom element constructors or invariant checks. This closes https://github.com/w3c/webcomponents/issues/569 by moving the catch-and-return-HTMLUnknownElement from HTML to DOM; HTML will subsequently be updated to remove that logic.
/cc @rniwa @dominiccooney. HTML PR incoming; I am hoping @rniwa can upstream his test changes from https://bugs.webkit.org/attachment.cgi?id=290872&action=prettypatch
=> Change createElement to report exceptions instead of rethrowing

dom.bs, dom.html
Fixes #187. Follow up work in HTML is tracked in
https://github.com/whatwg/html/issues/1713.
=> Redesign fire an event and target override

dom.bs, dom.html
…Target are identical
Change the behavior of event dispatch as follows:
1. Make an event dispatch happen until the root of the tree when target
and relatedTarget are identical in synthetic events.
2. Do not dispatch an event when retargeted-target and
retargeted-reletedTarget are identical, but target and relatedTarget are
not identical.
(2) is a bug fix. This sitution happens in UA events. For example,
if a mouse pointer moves from an element in a shadow tree to
its shadow host, a "mouseover" event should not be dispatched on the
shadow host. The current spec allows a non-empty event path in this case.
Fixes https://github.com/w3c/webcomponents/issues/577
=> Do not dispatch a trusted event when target and reletedTarget are identical

dom.bs, dom.html
This can be useful when you can’t use fire, but need to initialize
event attributes in a particular manner or keep the event around for
some reason.
Note that creating events without a constructor doesn’t work, as you
would not get the dictionary to usefully default attribute values.
=> Editorial: provide a shorthand for other specifications to create events

dom.bs, dom.html
Closes #352.
Some tests at https://github.com/w3c/web-platform-tests/pull/4088, but they are not exhaustive. I don't feel up to the task of writing a test for every instance of "fire" in the spec.
=> Use the relevant realm of the event target when firing an event

dom.bs
SVGZoomEvent has been removed from SVG and from Chromium:
https://github.com/w3c/svgwg/issues/21
https://crbug.com/367890
Fixes #283.
=> Drop support for SVGZoomEvent in createEvent

dom.bs
createElement/createElementNS disallowed upgrading of customized
built-in elements, incorrectly. Instead we should allow { is } to be
supplied and even if there is no corresponding definition now, it will
be upgraded later.
Fixes https://github.com/w3c/webcomponents/issues/608.
=> Remove incorrect customized built-in element checks

dom.bs
Fixes #378.
Tests: https://github.com/w3c/web-platform-tests/issues/4268.
=> Copy the origin pointer when cloning a document

dom.bs
More delightful garbage from the past. Fixes #211.
=> Add Event's cancelBubble attribute

dom.bs
See https://github.com/w3c/IndexedDB/issues/28
=> Point to HTML for DOMStringList

dom.bs
Indexed Database API could have done with some architectural design
review.
See https://github.com/w3c/IndexedDB/issues/140 for context.
=> Add legacyOutputDidListenersThrowFlag to event dispatch for IDB

dom.bs
Per https://github.com/w3c/web-platform-tests/issues/2499#issuecomment-172901580 this step is redundant.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/no-op-range-mutations/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/2358735...653fc60.html)
=> Remove no-op range mutations from split a Text node

dom.bs
Found via https://github.com/whatwg/infra/issues/6.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/infra-set-parser/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/334428f...9efdfd7.html)
=> Editorial: use Infra to define the ordered set parser

dom.bs
Tests: https://github.com/w3c/web-platform-tests/pull/5158.
Fixes #289.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/progressevent/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/334428f...41eb09c.html)
=> No longer support ProgressEvent in createEvent()

dom.bs
Fixes part of https://github.com/whatwg/html/issues/2381. The other
part is covered by https://github.com/whatwg/html/pull/2457.
Cannot be merged until https://github.com/heycam/webidl/pull/328 is also merged and the cross-spec linking database has been populated.
Tests: https://github.com/w3c/web-platform-tests/pull/5208
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/custom-element-construct/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/6253e53...ddeaa7f.html)
=> Use Web IDL to construct custom element constructors

dom.bs
Tests: https://github.com/w3c/web-platform-tests/issues/5161.
Fixes #319.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/name-validation/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/334428f...24569d8.html)
=> Use a single exception for name validation

dom.bs
In particular, define them as operations on an object’s children, which
is now defined to be an ordered set.
Fixes #174. (Note that we don’t have to define how the various pointers
mentioned there are updated, since those are all ultimately based on
how parent/child are defined.)
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/tree-manipulation/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/6ba16e7...9a7e1ea.html)
=> Be more precise about removal and insertion

dom.bs
In https://github.com/heycam/webidl/pull/286 we updated Web IDL so that
the extended attribute [TreatNullAs] now apply to types, not attributes.
This updates the spec's usage of [TreatNullAs] to conform to this.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/treatnullas-update/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/26faf9a...899def2.html)
=> Fix Web IDL extended attribute usage for recent changes

dom.bs
In particular when invoking toggle() and replace(). Also rewrite it in
terms of the Infra Standard.
Fixes #442 and fixes #443.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/domtokenlist/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/5f1a606...d7b281b.html)
=> Always update a DOMTokenList

dom.bs
Part of fixing https://github.com/whatwg/html/issues/2752. The "child text content" concept was previously defined in HTML, but is being moved here.
Probably shouldn't merge this until the corresponding HTML PR is ready and approved, in case there are some integration issues I missed out on, but I think this is reviewable as-is.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/child-text-content-changed/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/4512167...6a9b91f.html)
=> Add child text content and its change steps

dom.bs
This adds a previousSibling variable to the insert node algorithm in order to clarify that the previousSibling property of the mutation record generated by the insert node algorithm should be determined before inserting nodes. 
If implemented as described in the original text, the property would be determined after insertion, and will therefore always be the last of nodes.
***
[Preview](https://s3.amazonaws.com/pr-preview/bwrrp/dom/insertNode-MutationRecord-previousSibling.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/93db340...bwrrp:3927500.html)
=> Clarify insert-node's record's previousSibling

dom.bs
Fixes #447.
***
[Preview](https://s3.amazonaws.com/pr-preview/hayatoito/dom/slotchange-when-inserted.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/d9cd30d...hayatoito:e1db083.html)
=> Don't let a slot do anything special if it isn't in a shadow tree

dom.bs
Closes #441. See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=16487.
Tests: https://github.com/w3c/web-platform-tests/pull/6306
Chrome is interested in implementing this; anyone else? @cdumez @smaug---- @travisleithead
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/constructible-eventtarget/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/4512167...efad4c1.html)
=> Allow constructing and subclassing EventTarget

dom.bs
Update Event.timeStamp type to DOMHighResTimeStamp.
This fixes #23 and the commit contains the following changes:
- The text asks for the high resolution time of the event occurrence time to be used when
available and otherwise event object creation time.
- Add note in legacy section describing the change in semantic.
- Add note encouraging user agents to make high res time available for UI Events.
- Add necessary spec reference for Bikeshed to pick up new definitions in hr-time spec.
***
[Preview](https://s3.amazonaws.com/pr-preview/majido/dom/high-res-timestamp.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/334428f...majido:3f9f333.html)
=> Update Event.timeStamp type to DOMHighResTimeStamp.

dom.bs
Branched from https://github.com/whatwg/dom/pull/434
***
[Preview](https://s3.amazonaws.com/pr-preview/jakearchibald/dom/abort-controller.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/8f8c1c3...jakearchibald:0b8cce3.html)
=> Abort controller

dom.bs
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/origin-ascii/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/8f8c1c3...308dac6.html)
=> Origins serialize to ASCII these days

dom.bs
Uses https://github.com/whatwg/resources.whatwg.org/pull/53.
@annevk, if you could look over this and ideally https://github.com/whatwg/resources.whatwg.org/pull/53 as well, I'll merge them together once approved, and keep my finger hovering on the revert button in case anything goes wrong.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/service-worker/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/fba2caf...22611c0.html)
=> Meta: add a service worker to make the spec viewable offline

dom.bs
This is needed in the fetch spec to determine if a signal has already been aborted.
***
[Preview](https://s3.amazonaws.com/pr-preview/jakearchibald/dom/export-abort-flag.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/b8d9f4e...jakearchibald:fe36f19.html)
=> Export aborted flag

dom.bs
Fixes #362.  All of the removed event types except WheelEvent are
unsupported or are supported but cannot be properly initialized in
Blink, Gecko, and WebKit.  WheelEvent is supported in WebKit with a
vendor-prefixed initializer, but WebKit is willing to try dropping it.
***
[Preview](https://s3.amazonaws.com/pr-preview/ayg/dom/createEvent.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/4a58d67...ayg:cf75365.html)
=> Remove more types from document.createEvent()

dom.bs
The consistency change made in d396872f847d63b803393092eb81843e80d566b7
turned out to not be compatible with the web.
Fixes #451.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/toggle/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/5a532da...160d551.html)
=> DOMTokernList's toggle() cannot always update the attribute

dom.bs
This reverts ccf51e85, and fixes
https://www.w3.org/Bugs/Public/show_bug.cgi?id=25412.  It brings the
spec back in line with Firefox instead of other browsers.  Boris argues
convincingly that the behavior without the active flag is much harder to
spec and test properly, and nobody has a use-case for allowing recursion
here, so it's easier all around to converge on Firefox behavior and just
ban recursion.  He doesn't want Firefox to allow recursion unless
someone writes good tests for it, which nobody wants to.  Other UAs were
asked for comment on the bug and didn't support or oppose.
@bzbarsky @travisleithead @domenic @cdumez
***
[Preview](https://s3.amazonaws.com/pr-preview/ayg/dom/active-flag.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/61f40b0...ayg:2c0e1fe.html)
=> Reinstate active flag for iterators

dom.bs
According to annevk on #488, text is supposed to be wrapped to 100
columns, but the modeline says 76.  I made it 99 instead of 100 so that
diffs will be 100 columns and won't overflow if your terminal has a
width of 100, but it could be actually 100 too if we want.
***
[Preview](https://s3.amazonaws.com/pr-preview/ayg/dom/modeline.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/bcb0b3f...ayg:16da399.html)
=> Update width from 76 to 99 in vim modeline

dom.bs
Fixes #462.
***
[Preview](https://s3.amazonaws.com/pr-preview/ayg/dom/DOMTokenList-remove-noop.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/bcb0b3f...ayg:a06ca93.html)
=> DOMTokenList shouldn't add empty attributes

dom.bs
@RByers what do you think?
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/EventListenerOptions/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/aaf90dc...dcd948d.html)
=> Editorial: simplify EventListenerOptions processing

dom.bs
Helps with https://github.com/heycam/webidl/issues/365.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/exposed-window/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/da7b3ec...281db00.html)
=> Add [Exposed=Window] to MutationObserver

dom.bs
@domenic @annevk PTAL.
- Fixes #515.
- The full context on this change can be found [here](https://github.com/WebAudio/web-audio-api/issues/1266).
***
[Preview](https://s3.amazonaws.com/pr-preview/hoch/dom/515-expose-event-eventtarget-to-audioworklet.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/41db2a9...hoch:379e8e5.html)
=> Fix 515: Expose Event, EventTarget to AudioWorklet

dom.bs
Resolves whatwg/dom#511.
***
[Preview](https://s3.amazonaws.com/pr-preview/TakayoshiKochi/dom/squashing_target.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/601655d...TakayoshiKochi:22d1fb6.html)
=> Set event.target to null when dispatching finishes at ShadowRoot

dom.bs
This notably helps avoid confusion with ES errors (e.g. SyntaxError).
***
[Preview](https://s3.amazonaws.com/pr-preview/tobie/dom/domexceptions.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/9ada239...tobie:ab54d5d.html)
=> Editorial: use "exception name" DOMException notation

dom.bs
Fixes https://github.com/w3c/webcomponents/issues/570.
I'm somewhat surprised implementers haven't called this out meanwhile. Is this broken in implementations or does it end up working due to something else?
Anyone willing to write tests?
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/cereactions/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/da7b3ec...0606e9f.html)
=> Add [CEReactions] to createElement()

dom.bs
Fixes #525.
***
[Preview](https://dom.spec.whatwg.org/branch-snapshots/annevk/composedpath/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/dom/fb6638f...9857343.html)
=> Compute everything needed for composedPath() during dispatch

dom.bs
WebIDL recently introduced dedicated syntax for mixins[1]. So, we can
replace `[NoInterfaceObject]` and `implements` with `interface mixin` and
`includes`.
This following interfaces are impacted by this change:
- NonElementParentNode
- DocumentOrShadowRoot
- ParentNode
- NonDocumentTypeChildNode
- ChildNode
- Slotable
This fixes #532 issue.
Test: https://github.com/w3c/web-platform-tests/pull/8700
[1] https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
***
<a href="https://whatpr.org/dom/545.html" title="Last updated on Dec 18, 2017, 3:17 PM GMT (f632cf2)">Preview</a> | <a href="https://whatpr.org/dom/545/56ca18c...f632cf2.html" title="Last updated on Dec 18, 2017, 3:17 PM GMT (f632cf2)">Diff</a>
=> Use `interface mixins` instead of `[NoInterfaceObject]`

dom.bs
Fixes #555.
***
<a href="https://whatpr.org/dom/556.html" title="Last updated on Jan 6, 2018, 3:28 PM GMT (80f971c)">Preview</a> | <a href="https://whatpr.org/dom/556/5222eee...80f971c.html" title="Last updated on Jan 6, 2018, 3:28 PM GMT (80f971c)">Diff</a>
=> Use Infra's concatenation definition

dom.bs
So that other spec can actually use it.
***
<a href="https://whatpr.org/whatwg-dom/567.html" title="Last updated on Feb 3, 2018, 6:36 AM GMT (fe32384)">Preview</a> | <a href="https://whatpr.org/dom/567/676fcbe...fe32384.html" title="Last updated on Feb 3, 2018, 6:36 AM GMT (fe32384)">Diff</a>
=> Export attribute change steps

dom.bs
This PR makes it easier for one abort signal to follow another. This should avoid gotcha cases like https://github.com/whatwg/fetch/issues/668.
***
<a href="https://whatpr.org/dom/569.html" title="Last updated on Feb 12, 2018, 8:34 AM GMT (9ddd54f)">Preview</a> | <a href="https://whatpr.org/dom/569/cebdfa1...9ddd54f.html" title="Last updated on Feb 12, 2018, 8:34 AM GMT (9ddd54f)">Diff</a>
=> Following an abort signal

dom.bs
Part of fixing https://github.com/whatwg/html/issues/3402. This changes two things:
* It fixes the cloning steps to consult the internal is value, instead of the is="" content attribute.
* It removes the step from createElement()/createElementNS() that would insert an is="" attribute in the created element, as we've now decided that is="" is a way of communicating to the parser, and not a general-purpose indicator of customized built-in-ness.
---
This is coupled with a HTML change I will be submitting shortly, to the serializer (and to several examples).
@tkent-google, will you be able to help with tests for this? I am happy to review.
***
<a href="https://whatpr.org/dom/566.html" title="Last updated on Feb 2, 2018, 5:56 PM GMT (d510371)">Preview</a> | <a …
=> Change handling of is="" in element creation and cloning

dom.bs
They renamed "evaluate a selector" to "match a selector against a tree".
***
<a href="https://whatpr.org/dom/573.html" title="Last updated on Feb 19, 2018, 1:25 PM GMT (fa3a425)">Preview</a> | <a href="https://whatpr.org/dom/573/fc601be...fa3a425.html" title="Last updated on Feb 19, 2018, 1:25 PM GMT (fa3a425)">Diff</a>
=> Align with Selectors

dom.bs
This specifies a return value for DOMTokenList's `replace(token, newToken)` method, making it return true if token was replaced by newToken and false otherwise. This is useful for code which takes different paths depending on whether a replacement occurred, avoiding the need for an extra condition using `contains()`.
I have modified the [Element-classlist.html](https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Element-classlist.html) test to include [testing](https://gist.github.com/Zirro/b0fb873ccb86eb3bb6596833558abca4#file-element-classlist-html-L406) of this change, and will submit a pull request to the WPT repository if it is approved here.
Fixes #577.
***
<a href="https://whatpr.org/dom/582.html" title="Last updated on Mar 7, 2018, 6:10 PM GMT (fd0157c)">Preview</a> | …
=> Change DOMTokenList's replace() to return boolean

dom.bs
Fixes #297.
***
<a href="https://whatpr.org/dom/593.html" title="Last updated on Mar 13, 2018, 8:13 AM GMT (4bb937b)">Preview</a> | <a href="https://whatpr.org/dom/593/510fa87...4bb937b.html" title="Last updated on Mar 13, 2018, 8:13 AM GMT (4bb937b)">Diff</a>
=> Stop defining nodeName in terms of tagName

dom.bs
This hook ensures that any special casing in addEventListener() is shared with event handler attributes.
Helps with https://github.com/w3c/ServiceWorker/issues/1004.
***
<a href="https://whatpr.org/dom/596.html" title="Last updated on Mar 14, 2018, 8:35 AM GMT (4ebd185)">Preview</a> | <a href="https://whatpr.org/dom/596/8e754b5...4ebd185.html" title="Last updated on Mar 14, 2018, 8:35 AM GMT (4ebd185)">Diff</a>
=> Editorial: add "add an event listener" hook

dom.bs
This introduces the "inner event creation steps" so we don't duplicate a bunch of logic.
***
<a href="https://whatpr.org/dom/603.html" title="Last updated on Mar 16, 2018, 7:13 AM GMT (cfb07fa)">Preview</a> | <a href="https://whatpr.org/dom/603/06dae65...cfb07fa.html" title="Last updated on Mar 16, 2018, 7:13 AM GMT (cfb07fa)">Diff</a>
=> Make the two ways of event creation share a path

dom.bs
This refactors large parts of the DOM Standard to reclassify Range
objects as "live ranges" rather than "ranges". The bits shared
between StaticRange and Range objects are put on a shared superclass
named AbstractRange.
This also introduces a "collapsed" definition and uses it throughout.
It does not contain everything from
https://w3c.github.io/staticrange/. I based this draft on the IDL
present in implementations, coupled with the desire for a superclass.
Extensions beyond this seem best addressed as follow-ups.
Tests: ...
***
<a href="https://whatpr.org/dom/589.html" title="Last updated on Mar 16, 2018, 7:34 AM GMT (71954ff)">Preview</a> | <a href="https://whatpr.org/dom/589/06dae65...71954ff.html" title="Last updated on Mar 16, 2018, 7:34 AM GMT (71954ff)">Diff</a>
=> Add AbstractRange and StaticRange

dom.bs
Fixes #250.
***
<a href="https://whatpr.org/dom/595.html" title="Last updated on Mar 22, 2018, 6:57 AM GMT (06442ee)">Preview</a> | <a href="https://whatpr.org/dom/595/5f4249f...06442ee.html" title="Last updated on Mar 22, 2018, 6:57 AM GMT (06442ee)">Diff</a>
=> Editorial: expose surroundContents() comment

dom.bs
@whatwg/components this fixes the following:
* Adds "touch target list" as a concept hold by event, so touch events can be retargeted. (This will require some special handling for Touch objects, but I think it's workable.)
* It now resets target/relatedTarget/touch target list post-dispatch based on pre-dispatch conditions.
* It makes dispatch account for non-nodes.
(The one thing remaining here is having a good look at event constructors and making sure we can make that work for the relatedTargets design. I think that requires some kind of callback type thing.)
***
<a href="https://whatpr.org/dom/585.html" title="Last updated on Mar 27, 2018, 10:30 AM GMT (67e64b4)">Preview</a> | <a href="https://whatpr.org/dom/585/5be84cc...67e64b4.html" title="Last updated on Mar 27, 2018, 10:30 AM GMT …
=> Correct setting of target and relatedTargets post-dispatch

dom.bs
Fixes #132.
The main thing I still need to look into is figuring out how transient registered observers are actually removed, as the current text doesn't state that in much detail.
***
<a href="https://whatpr.org/dom/609.html" title="Last updated on Mar 29, 2018, 10:32 AM GMT (be1760f)">Preview</a> | <a href="https://whatpr.org/dom/609/787748d...be1760f.html" title="Last updated on Mar 29, 2018, 10:32 AM GMT (be1760f)">Diff</a>
=> Use Infra to define mutation observers

dom.bs
Fixes #570.
***
<a href="https://whatpr.org/dom/621.html" title="Last updated on Mar 30, 2018, 4:22 AM GMT (442c0b8)">Preview</a> | <a href="https://whatpr.org/dom/621/fc16564...442c0b8.html" title="Last updated on Mar 30, 2018, 4:22 AM GMT (442c0b8)">Diff</a>
=> Editorial: create a concept for event's target

dom.bs
This hook can be used by complex Event subclasses, such as KeyboardEvent and TouchEvent, to initialize their internal state upon creation.
Fixes #414.
***
<a href="https://whatpr.org/dom/614.html" title="Last updated on Mar 23, 2018, 12:46 PM GMT (b8e54d8)">Preview</a> | <a href="https://whatpr.org/dom/614/5be84cc...b8e54d8.html" title="Last updated on Mar 23, 2018, 12:46 PM GMT (b8e54d8)">Diff</a>
=> Define event constructing steps

dom.bs
wpt: https://github.com/w3c/web-platform-tests/pull/10258
r? @annevk
***
<a href="https://whatpr.org/dom/626.html" title="Last updated on Apr 9, 2018, 8:43 AM GMT (f6eb0e0)">Preview</a> | <a href="https://whatpr.org/dom/626/07c110c...f6eb0e0.html" title="Last updated on Apr 9, 2018, 8:43 AM GMT (f6eb0e0)">Diff</a>
=> Define Event.srcElement and Event.returnValue

dom.bs
The prose supposed to be equivalent to iterating over following siblings and siblings of ancestors did not skip over descendants.
See https://github.com/whatwg/dom/issues/87#issuecomment-374385254.
***
<a href="https://whatpr.org/dom/612.html" title="Last updated on Mar 22, 2018, 5:39 PM GMT (ae2fb6b)">Preview</a> | <a href="https://whatpr.org/dom/612/02f7143...ae2fb6b.html" title="Last updated on Mar 22, 2018, 5:39 PM GMT (ae2fb6b)">Diff</a>
=> Fix TreeWalker's nextNode()

dom.bs
Make the formatting consistent, avoid use of goto and labels, and be more clear about where various concepts are stored.
***
<a href="https://whatpr.org/dom/616.html" title="Last updated on Mar 23, 2018, 2:18 PM GMT (c9fce38)">Preview</a> | <a href="https://whatpr.org/dom/616/5be84cc...c9fce38.html" title="Last updated on Mar 23, 2018, 2:18 PM GMT (c9fce38)">Diff</a>
=> Editorial: cleanup TreeWalker

dom.bs
Mostly so I remember it's not just events.
Fixes #620.
***
<a href="https://whatpr.org/dom/630.html" title="Last updated on Apr 9, 2018, 2:03 PM GMT (b757081)">Preview</a> | <a href="https://whatpr.org/dom/630/7daecff...b757081.html" title="Last updated on Apr 9, 2018, 2:03 PM GMT (b757081)">Diff</a>
=> Note retargeting usage in Fullscreen

dom.bs
This is needed for document.open(): https://github.com/whatwg/html/issues/2302.
***
<a href="https://whatpr.org/dom/641.html" title="Last updated on Apr 27, 2018, 3:24 PM GMT (4b7bb04)">Preview</a> | <a href="https://whatpr.org/dom/641/4b2633f...4b7bb04.html" title="Last updated on Apr 27, 2018, 3:24 PM GMT (4b7bb04)">Diff</a>
=> Introduce "remove all event listeners" primitive

dom.bs
It's never really unambiguous to omit it.
***
<a href="https://whatpr.org/dom/647.html" title="Last updated on May 18, 2018, 2:23 PM GMT (b3b21e3)">Preview</a> | <a href="https://whatpr.org/dom/647/21e7ec3...b3b21e3.html" title="Last updated on May 18, 2018, 2:23 PM GMT (b3b21e3)">Diff</a>
=> No longer allow the context object to be omitted

dom.bs
The twitter link in the header was changed unintentionally from [@thedomstandard](https://twitter.com/thedomstandard) to [@domstandard](https://twitter.com/domstandard) in commit https://github.com/whatwg/dom/commit/4953b84021fbeaf27df63c6c437e673f5db3c197.
***
<a href="https://whatpr.org/dom/649.html" title="Last updated on May 22, 2018, 10:26 AM GMT (ca87be4)">Preview</a> | <a href="https://whatpr.org/dom/649/927e917...ca87be4.html" title="Last updated on May 22, 2018, 10:26 AM GMT (ca87be4)">Diff</a>
=> Meta: fix link to the DOM Standard twitter page

dom.bs
cf. #334 
@annevk is this sufficient? Or should I add `srcElement` everywhere that `target` is mentioned (feels a bit redundant after a while...)
I'll have a related wpt PR tomorrow at some point.
***
<a href="https://whatpr.org/dom/407.html" title="Last updated on Jun 4, 2018, 10:18 AM GMT (acc8ede)">Preview</a> | <a href="https://whatpr.org/dom/407/eb0db13...acc8ede.html" title="Last updated on Jun 4, 2018, 10:18 AM GMT (acc8ede)">Diff</a>
=> Add window.event as a legacy compat requirement

dom.bs
This makes it so that if the `DOMTokenList`'s associated element has an attribute that is the associated attribute's local name, at creation time, it will use the "get an attribute value" steps, which will always return a string. Previously, the this used the "get an attribute by namespace and local name" steps, which would return an `Attr` node if the associated element had an attribute that is the associated attribute's local name. Fixes #666.
***
<a href="https://whatpr.org/dom/673.html" title="Last updated on Aug 1, 2018, 12:31 AM GMT (2ff522f)">Preview</a> | <a href="https://whatpr.org/dom/673/32efc48...2ff522f.html" title="Last updated on Aug 1, 2018, 12:31 AM GMT (2ff522f)">Diff</a>
=> Make the DOMTokenList creation steps use "get an attribute value"

dom.bs
fc165642b437c548a11222c85ddda0094ed40ea5 did not adequately consider the global object.
Fixes #697.
***
<a href="https://whatpr.org/dom/698.html" title="Last updated on Sep 17, 2018, 9:31 AM GMT (0e3e225)">Preview</a> | <a href="https://whatpr.org/dom/698/42d2485...0e3e225.html" title="Last updated on Sep 17, 2018, 9:31 AM GMT (0e3e225)">Diff</a>
=> Avoid setting target to the Window object

dom.bs
The existing algorithm exposed nodes in shadow trees that should remain hidden. (This wasn't noticed in #535.)
This roughly matches the approach taken by jsdom to solve this issue and unlike #696 requires no downstream changes.
Tests: ...
Fixes #684.
***
<a href="https://whatpr.org/dom/699.html" title="Last updated on Sep 18, 2018, 10:34 AM GMT (60b4d4a)">Preview</a> | <a href="https://whatpr.org/dom/699/0b04ae8...60b4d4a.html" title="Last updated on Sep 18, 2018, 10:34 AM GMT (60b4d4a)">Diff</a>
=> Fix composedPath() once more

dom.bs
The comparison needs to be 'less than or equal', otherwise you don't prepend the items from the same level as the target.
Trivially, in a 'no shadow DOM' situation, all the items in the path before the current target wouldn't be in the path without this patch, which is wrong.
This is tested already by event-composed-path.html in WPT.
***
<a href="https://whatpr.org/dom/727.html" title="Last updated on Dec 29, 2018, 6:42 PM UTC (157b3af)">Preview</a> | <a href="https://whatpr.org/dom/727/ee24b02...157b3af.html" title="Last updated on Dec 29, 2018, 6:42 PM UTC (157b3af)">Diff</a>
=> Fix a small but important error in composedPath()

dom.bs
First crack at first spec change.
Addresses https://github.com/whatwg/dom/issues/664
***
<a href="https://whatpr.org/dom/722.html" title="Last updated on Dec 10, 2018, 9:44 AM GMT (6c15c49)">Preview</a> | <a href="https://whatpr.org/dom/722/23ec642...6c15c49.html" title="Last updated on Dec 10, 2018, 9:44 AM GMT (6c15c49)">Diff</a>
=> Add a note about duplicate event listeners for removeEventListener

dom.bs
Using "unit of related similar-origin browsing contexts" never made much sense as a browsing context could always hold several cross-site documents.
Helps with https://github.com/whatwg/html/issues/4198.
Fixes #88.
***
<a href="https://whatpr.org/dom/717.html" title="Last updated on Jan 16, 2019, 12:34 PM UTC (66d734c)">Preview</a> | <a href="https://whatpr.org/dom/717/15e2f41...66d734c.html" title="Last updated on Jan 16, 2019, 12:34 PM UTC (66d734c)">Diff</a>
=> Ground primitives in agents

dom.bs
Instead of shoehorning all target handling into the bubbling iteration, this separates "capturing" iteration from "bubbling" iteration and the Event object's phase is set to target as appropriate in both.
This also invokes the event listeners in a more natural order.
Tests: ...
Fixes #685.
***
<a href="https://whatpr.org/dom/686.html" title="Last updated on Mar 1, 2019, 10:49 AM UTC (7aaff50)">Preview</a> | <a href="https://whatpr.org/dom/686/42d2485...7aaff50.html" title="Last updated on Mar 1, 2019, 10:49 AM UTC (7aaff50)">Diff</a>
=> Fix event path iteration

dom.bs
This is needed for defining HTML's output element. See https://github.com/whatwg/html/issues/4163 for context.
***
<a href="https://whatpr.org/dom/743.html" title="Last updated on Mar 26, 2019, 12:54 PM UTC (20be836)">Preview</a> | <a href="https://whatpr.org/dom/743/9943801...20be836.html" title="Last updated on Mar 26, 2019, 12:54 PM UTC (20be836)">Diff</a>
=> Create an abstraction for Element's textContent getter

dom.bs
Complements https://github.com/whatwg/html/pull/4437.
Also clarify which agent the mutation observer microtask queued member is obtained from.
Fixes #734.
***
<a href="https://whatpr.org/dom/741.html" title="Last updated on Mar 22, 2019, 1:06 PM UTC (5a763a6)">Preview</a> | <a href="https://whatpr.org/dom/741/9943801...5a763a6.html" title="Last updated on Mar 22, 2019, 1:06 PM UTC (5a763a6)">Diff</a>
=> Remove compound microtasks

dom.bs
This fixes a regression from #686.
Tests: various tests were failing because of this. https://github.com/web-platform-tests/wpt/pull/16307 aligns the remaining failing test with the new model.
Fixes #742.
=> Non-bubbling event should run non-capture listeners

dom.bs
Per https://github.com/whatwg/html/pull/4525 a custom element constructor is required to be an HTMLElement.
Also, rather than assume another specification will make foreign namespace objects implement HTMLElement, let's instead assert that does not happen as we cannot test it.
=> Editorial: use IDL to simplify create an element

dom.bs
Discussed in #760. This makes the various cases less distinguishable,
which is desirable. With this change, all three cases behave the same
between:
- A custom element with disabled-shadow
- A custom element with a shadow tree
- A built-in element on the blocklist
Tests: https://github.com/web-platform-tests/wpt/pull/16853
***
<a href="https://whatpr.org/dom/761.html" title="Last updated on May 15, 2019, 7:09 PM UTC (7bcdca6)">Preview</a> | <a href="https://whatpr.org/dom/761/e4e0ea8...7bcdca6.html" title="Last updated on May 15, 2019, 7:09 PM UTC (7bcdca6)">Diff</a>
=> Use "NotSupportedError" when trying to attachShadow() twice

dom.bs
This fixes a part of https://github.com/w3c/webcomponents/issues/758
This and https://github.com/whatwg/html/pull/4324 should be merged at the same time.
Test: https://github.com/web-platform-tests/wpt/pull/16795
***
<a href="https://whatpr.org/dom/760.html" title="Last updated on May 16, 2019, 4:14 PM UTC (2982935)">Preview</a> | <a href="https://whatpr.org/dom/760/bcdab96...2982935.html" title="Last updated on May 16, 2019, 4:14 PM UTC (2982935)">Diff</a>
=> Add "disable shadow" flag check to Element.attachShadow()

dom.bs
As pointed out at https://github.com/whatwg/dom/pull/695#pullrequestreview-233547961 it would be nice if this were more consistent.
***
<a href="https://whatpr.org/dom/762.html" title="Last updated on May 20, 2019, 2:38 PM UTC (09c786e)">Preview</a> | <a href="https://whatpr.org/dom/762/daa525d...09c786e.html" title="Last updated on May 20, 2019, 2:38 PM UTC (09c786e)">Diff</a>
=> Editorial: use Infra list syntax in mutations

dom.bs
The Selection API makes extensive reference to the "collapsed" concept. It's currently explicitly linked through an absolute URL. Alternatively, it might be nice to export it in such a way that it can be used via [=range/collapsed=] - for whatever  reason, that form is not being exposed to BikeShed/Shepherd's data.
***
<a href="https://whatpr.org/dom/764.html" title="Last updated on Jun 4, 2019, 6:58 AM UTC (74343da)">Preview</a> | <a href="https://whatpr.org/dom/764/0f0d1b6...74343da.html" title="Last updated on Jun 4, 2019, 6:58 AM UTC (74343da)">Diff</a>
=> Export concept of collapsed

dom.bs
See https://github.com/heycam/webidl/pull/750.
***
<a href="https://whatpr.org/dom/771.html" title="Last updated on Aug 8, 2019, 3:50 PM UTC (810f321)">Preview</a> | <a href="https://whatpr.org/dom/771/b5eac4d...810f321.html" title="Last updated on Aug 8, 2019, 3:50 PM UTC (810f321)">Diff</a>
=> Align with IDL dictionary changes

dom.bs
Either way is correct IDL, but this seems better for the reader (and changes less if you ignore the prior commit).
***
<a href="https://whatpr.org/dom/775.html" title="Last updated on Aug 9, 2019, 8:02 AM UTC (1a941ed)">Preview</a> | <a href="https://whatpr.org/dom/775/c15e65f...1a941ed.html" title="Last updated on Aug 9, 2019, 8:02 AM UTC (1a941ed)">Diff</a>
=> Editorial: attachShadow() takes a required dictionary

dom.bs
https://wiki.whatwg.org/wiki/DOM_XPath
Related: https://github.com/whatwg/dom/issues/67
***
<a href="https://whatpr.org/dom/763.html" title="Last updated on Aug 30, 2019, 8:19 AM UTC (5f1b1e0)">Preview</a> | <a href="https://whatpr.org/dom/763/a93f9f8...5f1b1e0.html" title="Last updated on Aug 30, 2019, 8:19 AM UTC (5f1b1e0)">Diff</a>
=> Copy the DOM XPath interfaces from the WHATWG wiki

dom.bs
This changes addEventListener() and removeEventListener() to not throw even
after the very first evalution of the service worker script. Instead, this
specifies user agents have to show a console warning that the asynchronously
added listener's event type will not affect service worker's behavior with the
functional event stored during the first evaluation.
This change referneces the funcional event concept defined in Service Workers
spec, and confines the EventTarge object of the specified behavior to
ServiceWorkerGlobalScope object instead of all the platform object in the global
object.
Related SW issue: https://github.com/w3c/ServiceWorker/issues/1004.
Related SW PR: https://github.com/w3c/ServiceWorker/pull/1322.
Fixes https://github.com/whatwg/dom/issues/371.
***
<a …
=> Change add/remove event listener behavior for service workers

dom.bs
It needs to be "children changed steps" as the various consumers appear to react to changes of all sorts.
Tests: https://github.com/web-platform-tests/wpt/pull/15871.
This builds on work started in #732 and will further refine that eventually.
***
<a href="https://whatpr.org/dom/800.html" title="Last updated on Dec 6, 2019, 11:19 AM UTC (407b19b)">Preview</a> | <a href="https://whatpr.org/dom/800/49f009a...407b19b.html" title="Last updated on Dec 6, 2019, 11:19 AM UTC (407b19b)">Diff</a>
=> Replace child text content change steps

dom.bs
Also clean up the language around DocumentFragment nodes in this algorithm a bit.
Tests: https://github.com/web-platform-tests/wpt/pull/20659.
***
<a href="https://whatpr.org/dom/806.html" title="Last updated on Dec 6, 2019, 3:46 PM UTC (6d21b71)">Preview</a> | <a href="https://whatpr.org/dom/806/37d8475...6d21b71.html" title="Last updated on Dec 6, 2019, 3:46 PM UTC (6d21b71)">Diff</a>
=> Insertion of empty DocumentFragment is a no-op

dom.bs
And do not allow non-null host DocumentFragment nodes to be adopted.
This means that a DocumentFragment is no longer implicitly adopted and a DocumentFragment with a non-null host cannot be put in a "weird" state.
Tests: https://github.com/web-platform-tests/wpt/pull/16348.
Fixes #744.
***
<a href="https://whatpr.org/dom/754.html" title="Last updated on Dec 6, 2019, 1:48 PM UTC (6aec9ae)">Preview</a> | <a href="https://whatpr.org/dom/754/37d8475...6aec9ae.html" title="Last updated on Dec 6, 2019, 1:48 PM UTC (6aec9ae)">Diff</a>
=> Run adopt as part of insert

dom.bs
Closes #801.
***
<a href="https://whatpr.org/dom/805.html" title="Last updated on Dec 11, 2019, 5:34 PM UTC (6ad5327)">Preview</a> | <a href="https://whatpr.org/dom/805/37d8475...6ad5327.html" title="Last updated on Dec 11, 2019, 5:34 PM UTC (6ad5327)">Diff</a>
=> Editorial: embrace that attributes are objects

dom.bs
Use self.origin instead. (The document's origin internal concept is kept for now. Maybe at some point we can only use that of the relevant global object, but not now.)
Tests: ...
Closes #410.
***
<a href="https://whatpr.org/dom/815.html" title="Last updated on Jan 2, 2020, 8:09 AM UTC (7e2469c)">Preview</a> | <a href="https://whatpr.org/dom/815/0913dac...7e2469c.html" title="Last updated on Jan 2, 2020, 8:09 AM UTC (7e2469c)">Diff</a>
=> Remove document.origin

dom.bs
Fixes #788.
***
<a href="https://whatpr.org/dom/820.html" title="Last updated on Jan 16, 2020, 2:04 PM UTC (2b7b081)">Preview</a> | <a href="https://whatpr.org/dom/820/55379a7...2b7b081.html" title="Last updated on Jan 16, 2020, 2:04 PM UTC (2b7b081)">Diff</a>
=> Editorial: add missing comma in "add an event listener" definition

dom.bs
In [**replace all**](https://dom.spec.whatwg.org/#concept-node-replace-all), `addedNodes` is either a _list_ (step 2) or a _set_ (step 3).
In [**replace**](https://dom.spec.whatwg.org/#concept-node-replace), `removedNodes` has only one element and can be safely changed to a _set_ to match type of `removedNodes` in [**replace all**](https://dom.spec.whatwg.org/#concept-node-replace-all) and [**insert**](https://dom.spec.whatwg.org/#concept-node-insert).
***
<a href="https://whatpr.org/dom/823.html" title="Last updated on Jan 22, 2020, 3:05 PM UTC (8f1c413)">Preview</a> | <a href="https://whatpr.org/dom/823/86e53d5...8f1c413.html" title="Last updated on Jan 22, 2020, 3:05 PM UTC (8f1c413)">Diff</a>
=> Editorial: make type of {added,removed}Nodes consistent

dom.bs
Fixes #796.
***
<a href="https://whatpr.org/dom/822.html" title="Last updated on Jan 22, 2020, 3:23 PM UTC (de10bc3)">Preview</a> | <a href="https://whatpr.org/dom/822/55379a7...de10bc3.html" title="Last updated on Jan 22, 2020, 3:23 PM UTC (de10bc3)">Diff</a>
=> Avoid enqueuing tree mutation record when there is no mutation

dom.bs
I've updated the content object definition so it's an alias of this (and added a note). But if we're happy to force all specs to change, I can just remove these lines. Up to you.
***
<a href="https://whatpr.org/dom/824.html" title="Last updated on Jan 23, 2020, 10:06 PM UTC (ee795e4)">Preview</a> | <a href="https://whatpr.org/dom/824/d4535b4...ee795e4.html" title="Last updated on Jan 23, 2020, 10:06 PM UTC (ee795e4)">Diff</a>
=> Replacing 'context object' with 'this'

dom.bs
Fixes #773.
***
<a href="https://whatpr.org/dom/827.html" title="Last updated on Feb 3, 2020, 12:43 AM UTC (09213bf)">Preview</a> | <a href="https://whatpr.org/dom/827/e15774f...09213bf.html" title="Last updated on Feb 3, 2020, 12:43 AM UTC (09213bf)">Diff</a>
=> Avoid enqueuing "disconnectedCallback" on detached custom elements

dom.bs
While preserving IDs. Closes #844.
(This also requires a corresponding change to HTML.)
***
<a href="https://whatpr.org/dom/845.html" title="Last updated on Mar 11, 2020, 9:08 AM UTC (3026fbe)">Preview</a> | <a href="https://whatpr.org/dom/845/b4e91f5...3026fbe.html" title="Last updated on Mar 11, 2020, 9:08 AM UTC (3026fbe)">Diff</a>
=> Editorial: slotable ➡️ slottable

dom.bs
[TreatNullAs=EmptyString] → [LegacyNullToEmptyString] and [Unforgeable] →
[LegacyUnforgeable]. Follows https://github.com/heycam/webidl/pull/870.
This should be merged after that, plus a day or so for the linking database to pick up the new name.
***
<a href="https://whatpr.org/dom/856.html" title="Last updated on Apr 8, 2020, 9:42 PM UTC (c4fb6e5)">Preview</a> | <a href="https://whatpr.org/dom/856/61834f7...c4fb6e5.html" title="Last updated on Apr 8, 2020, 9:42 PM UTC (c4fb6e5)">Diff</a>
=> Align with Web IDL extended attribute changes

dom.bs
Closes https://github.com/whatwg/html/issues/5084. /cc @tkent-google @bzbarsky and also @mfreed7 since he's been working on custom element bugs in Chromium recently.
This needs tests; maybe one of you all would be able to adapt the code in https://github.com/whatwg/html/issues/5084 into such tests? Be sure to test the question as to whether the element retains its identity or not.
***
<a href="https://whatpr.org/dom/797.html" title="Last updated on Dec 2, 2019, 8:33 PM UTC (c1b5bd4)">Preview</a> | <a href="https://whatpr.org/dom/797/49f009a...c1b5bd4.html" title="Last updated on Dec 2, 2019, 8:33 PM UTC (c1b5bd4)">Diff</a>
=> Catch errors while upgrading customized built-in elements

dom.bs
As discussed in #745, I made the required changes for clarification on the shadow element's local name.
It follows the formate specified in https://github.com/whatwg/dom/issues/745#issuecomment-639329890 by @annevk.
A side note:
There was an error during the `make` process, on both unedited and edited versions of dom.bs
```txt
Error running preprocessor, returned code: 1.
LINK ERROR: No 'dfn' refs found for 'case-sensitive' that are marked for export.
&lt;a data-link-type="dfn" data-lt="case-sensitive">case-sensitive&lt;/a>
✘  Did not generate, due to fatal errors
make: *** [Makefile:5: remote] Error 22
```
Due to which I couldn't verify my changes, so please let me know if something is off : )
***
<a href="https://whatpr.org/dom/869.html" title="Last updated on Jun 8, 2020, 8:18 AM UTC …
=> Clarification on valid shadow element's local name

dom.bs
Fixes #888.
***
<a href="https://whatpr.org/dom/890.html" title="Last updated on Sep 9, 2020, 10:35 AM UTC (cd802c8)">Preview</a> | <a href="https://whatpr.org/dom/890/8f20138...cd802c8.html" title="Last updated on Sep 9, 2020, 10:35 AM UTC (cd802c8)">Diff</a>
=> DOM Events introduction: clarify how listeners are invoked

dom.bs
Add the "precustomized" state needed by the [HTML PR](https://github.com/whatwg/html/pull/5909) that prevents usage of `attachInternals()` prior to the constructor being run.
* Chromium: me
* Safari: based on [this comment](https://github.com/w3c/webcomponents/issues/871#issuecomment-690879744)
* https://github.com/web-platform-tests/wpt/pull/25402
* Chrome: Tracked as part of the declarative Shadow DOM [tracking bug](https://crbug.com/1042130).
* Firefox: none yet
* Safari: none yet
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 28, 2020, 11:11 AM UTC)_.
<details>
:rotating_light: [CSS Spec …
=> Add "precustomized" custom element state

dom.bs
Add `"is available to element internals"` flag, for use with the accompanying [HTML PR](https://github.com/whatwg/html/pull/5912) which restricts access to `ElementInternals.shadowRoot` for shadow roots which were pre-existing before a custom element upgrade/construction. See the discussion on [Issue 871](https://github.com/w3c/webcomponents/issues/871#issuecomment-692383222) for more context.
* Chromium - me.
* WebKit: see [this comment](https://github.com/w3c/webcomponents/issues/871#issuecomment-692383222).
* https://github.com/web-platform-tests/wpt/pull/25554
* Chrome: https://crbug.com/1042130
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/dom/893.html" title="Last updated on Oct 5, 2020, 4:20 PM UTC (8625fe7)">Preview</a> | <a …
=> Add is-available-to-element-internals

dom.bs
Now that the default semantics are to throw, we need to be more explicit about catching.
***
<a href="https://whatpr.org/dom/889.html" title="Last updated on Sep 8, 2020, 3:01 PM UTC (3b1370a)">Preview</a> | <a href="https://whatpr.org/dom/889/8f20138...3b1370a.html" title="Last updated on Sep 8, 2020, 3:01 PM UTC (3b1370a)">Diff</a>
=> Need to catch exceptions to report them

dom.bs
Fixes #924
***
<a href="https://whatpr.org/dom/925.html" title="Last updated on Nov 17, 2020, 11:36 PM UTC (44eecc3)">Preview</a> | <a href="https://whatpr.org/dom/925/52f7a52...44eecc3.html" title="Last updated on Nov 17, 2020, 11:36 PM UTC (44eecc3)">Diff</a>
=> Fix the comparing boundary points of `concept-range-bp-set`

dom.bs
***
<a href="https://whatpr.org/dom/935.html" title="Last updated on Dec 21, 2020, 2:31 PM UTC (6538936)">Preview</a> | <a href="https://whatpr.org/dom/935/83037a1...6538936.html" title="Last updated on Dec 21, 2020, 2:31 PM UTC (6538936)">Diff</a>
=> Use undefined union for Window.event

dom.bs
It needs to pass this rather than an undefined variable. Also clean up the algorithm a bit.
Fixes #921.
***
<a href="https://whatpr.org/dom/923.html" title="Last updated on Jan 19, 2021, 11:20 AM UTC (fd6673c)">Preview</a> | <a href="https://whatpr.org/dom/923/8f3ee85...fd6673c.html" title="Last updated on Jan 19, 2021, 11:20 AM UTC (fd6673c)">Diff</a>
=> Correct step in matches()

dom.bs
Once you have thrown for all QName cases, you can no longer throw for Name cases. Tested as part of #423.
Also cleanup createElementNS() domintro.
Fixes #671 and closes #675.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 27, 2021, 5:19 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Fdom%2F37d704849195682c1c680849f3e9ce6abbb4c0da%2Fdom.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER% …
=> Use a single exception for name validation (follow-up)

dom.bs
A comma got dropped in https://github.com/whatwg/dom/commit/83037a1 but the sentence it’s in isn’t grammatical without it, so this change restores it.
***
<a href="https://whatpr.org/dom/954.html" title="Last updated on Feb 28, 2021, 1:32 AM UTC (a2ae3c9)">Preview</a> | <a href="https://whatpr.org/dom/954/c80cbf5...a2ae3c9.html" title="Last updated on Feb 28, 2021, 1:32 AM UTC (a2ae3c9)">Diff</a>
=> Editorial: Restore necessary comma

dom.bs
Hi, I was reading through the [AbortSignal](https://dom.spec.whatwg.org/#interface-AbortSignal) specs and found this typo. So here is my first contribution to WHATWG ☺️
Cheers.
***
<a href="https://whatpr.org/dom/962.html" title="Last updated on Mar 14, 2021, 8:19 PM UTC (c40bad9)">Preview</a> | <a href="https://whatpr.org/dom/962/aa384af...c40bad9.html" title="Last updated on Mar 14, 2021, 8:19 PM UTC (c40bad9)">Diff</a>
=> Editorial: fix typo

dom.bs
The explainer for this feature is here: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md
The issue discussion is here: [3534](https://github.com/whatwg/html/issues/3534)
There is a corresponding [Pull Request](https://github.com/whatwg/html/pull/6561) for the HTML spec that goes along with this PR.
* Chromium tracking bug is [here](http://crbug.com/1196842), with the original implementation tracker [here](http://crbug.com/869308).
* The implementation is based on what was agreed in the last [F2F Meeting](https://github.com/whatwg/html/issues/3534#issuecomment-537802687).
* In WPT: https://wpt.fyi/results/shadow-dom/slots-imperative-slot-api.tentative.html?label=master&label=experimental&aligned&q=slots-imperative-slot-api.tentative.html …
=> Add Imperative Slot API

dom.bs
In particular adopt the getter/setter/method/constructor steps pattern.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 15, 2021, 12:27 PM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwhatpr.org%2Fdom%2F969%2Facfe96b.html&doc2=https%3A%2F%2Fwhatpr.org%2Fdom%2F969.html)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body> …
```
=> Editorial: major change to align with IDL and Infra

dom.bs
Copied from https://wiki.whatwg.org/wiki/DOM_XSLTProcessor.
Part of https://github.com/whatwg/dom/issues/181.
* Already shipped for a very long time.
* https://wpt.fyi/results/xslt/idlharness.tentative.window.html?run_id=5629877849948160&run_id=5674415519956992&run_id=5740158517248000&run_id=5649823409635328
***
<a href="https://whatpr.org/dom/972.html" title="Last updated on Apr 16, 2021, 7:49 AM UTC (97202ee)">Preview</a> | <a href="https://whatpr.org/dom/972/a73380f...97202ee.html" title="Last updated on Apr 16, 2021, 7:49 AM UTC (97202ee)">Diff</a>
=> Add the IDL of XSLTProcessor

dom.bs
Fixes https://github.com/whatwg/dom/issues/931.
* Chrome: Shipped a long time ago (unclear if the lack of a spec was known)
* Firefox: @smaug---- says "[shouldn't be harmful](https://github.com/whatwg/dom/issues/931#issuecomment-741928360)"
* Safari: @rniwa says "[I'll be in the favor for adding this readonly attribute to make the API more interoperable.](https://github.com/whatwg/dom/issues/931#issuecomment-742821660)"
* https://github.com/web-platform-tests/wpt/pull/28593
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1706275
* Safari: https://bugs.webkit.org/show_bug.cgi?id=224805
***
<a href="https://whatpr.org/dom/974.html" title="Last updated on Apr 20, 2021, 8:46 AM UTC …
=> Add ShadowRoot.prototype.delegatesFocus attribute

dom.bs
Fixes #999.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 21, 2021, 2:23 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Fdom%2F1eadf0a4a271acc92013d1c0de8c730ac96204f9%2Fdom.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%201002)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1> …
```
=> Pass eventInitDict to event constructing steps

dom.bs
Add criteria defining whether a StaticRange is valid.
This will be used by the CSS [Highlight API](https://drafts.csswg.org/css-highlight-api-1/) to determine whether or not to paint highlights specified by StaticRanges. See https://drafts.csswg.org/css-highlight-api-1/#range-invalidation (which will be updated to point to the DOM spec definition) and the CSSWG [resolution](https://github.com/w3c/csswg-drafts/issues/4597#issuecomment-905688814) that Highlight API should use StaticRanges internally rather than backing them with live Ranges.
Resolves #947.
* Chromium has implemented Highlight API based on StaticRange using this validity criteria. 
* Webkit has implemented an experimental version of Highlight API, and agreed to the use of StaticRange per the [resolution …
=> Add validity criteria for StaticRange

dom.bs
1. Address numerous xref issues around the term node and prevent some from occurring for the term children.
2. Embrace Attr as a node even more.
3. Rely on Web IDL's implements and interface primitives to reduce the opportunities for confusion.
Fixes https://github.com/heycam/webidl/issues/659, #597, #636, #719, and #770.
***
<a href="https://whatpr.org/dom/1004.html" title="Last updated on Aug 31, 2021, 11:08 AM UTC (1b388b0)">Preview</a> | <a href="https://whatpr.org/dom/1004/f2a2ded...1b388b0.html" title="Last updated on Aug 31, 2021, 11:08 AM UTC (1b388b0)">Diff</a>
=> Revamp the way DOM talks about nodes

dom.bs
Also clean up some remaining instances that didn't use signal.reason.
Closes #961.
---
Some changes here are copied from #1032 and some could be further improved in #1034. Given that those will likely take a bit more I figured we should at least get this clarified while people are updating their APIs to account for signal's abort reason.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 6, 2021, 9:57 AM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related …
=> Aborting: clarify usage for non-promise APIs

dom.bs
Closes #927.
* Chromium
* Gecko
* https://github.com/web-platform-tests/wpt/pull/31947
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1273458
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1745372
* Safari: https://bugs.webkit.org/show_bug.cgi?id=234127
***
<a href="https://whatpr.org/dom/1034.html" title="Last updated on Dec 10, 2021, 8:37 AM UTC (0645ef6)">Preview</a> | <a href="https://whatpr.org/dom/1034/982c7e2...0645ef6.html" title="Last updated on Dec 10, 2021, 8:37 AM UTC (0645ef6)">Diff</a>
=> Introduce abortSignal.throwIfAborted()

dom.bs
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331
* Positive initial signals from Google, Apple, Mozilla on the general direction.
* https://github.com/web-platform-tests/wpt/pull/31852
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1281880
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1747059
* Safari: https://bugs.webkit.org/show_bug.cgi?id=234554
***
<a href="https://whatpr.org/dom/1024.html" title="Last updated on Dec 10, 2021, 2:24 PM UTC (15f19fb)">Preview</a> | <a href="https://whatpr.org/dom/1024/3c6704a...15f19fb.html" title="Last updated on Dec 10, 2021, 2:24 PM UTC (15f19fb)">Diff</a>
***
[PR …
=> Expose events/aborts everywhere

dom.bs
Closes #951.
This introduces a new static method, `AbortSignal.timeout(milliseconds)`, which returns a newly-created `AbortSignal` that, after `milliseconds` milliseconds, becomes automatically aborted. The `AbortSignal`'s `reason` property will be a `"TimeoutError"` `DOMException`.
The main motivating use case for this is helping web developers easily time out async operations, such as `fetch()`. For example, now you can write:
```js
fetch(url, { signal: AbortSignal.timeout(10_000) });
```
to ensure your fetch operation has a 10-second timeout. A more full example would be:
```js
try {
const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
const result = await res.text();
// ...
} catch (e) {
if (e.name === "TimeoutError") {
// It took more than 10 seconds to get the …
```
=> Introduce AbortSignal.timeout()

dom.bs
Worklets are designed with minimal event loops such that they need only run a single task and corresponding microtasks, making APIs that schedule additional tasks unsuitable for worklets. This restricts the availability of AbortSignal.timeout to Window and Worker since the API schedules a task to implement the timeout.
Closes #1054.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
* Deno (only for aborting and events): …
* Node.js (only for aborting and events): …
***
<a href="https://whatpr.org/dom/1055.html" title="Last updated on Feb 4, 2022, 8:50 PM UTC (9da62cc)">Preview</a> | <a href="https://whatpr.org/dom/1055/db4088a...9da62cc.html" title="Last updated on Feb 4, 2022, 8:50 PM UTC …
=> Limit AbortSignal.timeout to Window and Worker

dom.bs
Fixes #1065.
***
<a href="https://whatpr.org/dom/1066.html" title="Last updated on Mar 11, 2022, 11:27 AM UTC (6f783fe)">Preview</a> | <a href="https://whatpr.org/dom/1066/dbb7916...6f783fe.html" title="Last updated on Mar 11, 2022, 11:27 AM UTC (6f783fe)">Diff</a>
=> Correct extracting reference

dom.bs
@annevk said "that's not great" out loud. Twice!
***
<a href="https://whatpr.org/dom/1086.html" title="Last updated on Jun 9, 2022, 9:11 AM UTC (86e2614)">Preview</a> | <a href="https://whatpr.org/dom/1086/20012f1...86e2614.html" title="Last updated on Jun 9, 2022, 9:11 AM UTC (86e2614)">Diff</a>
=> Missing dot for `concept-node-remove`s first step.

dom.bs
This commit fixes a small typo in the id of the section https://dom.spec.whatwg.org/#action-versus-occurance.
Since this id is probably used in many places, we kept a `<span>` with the previous id to preserve the previous link (Thanks @sideshowbarker for the suggestion).
Ps: I'm not too used to bikeshed, but for whatever reasons it was requesting the id to be hardcoded, instead of deriving it from the title's content.
* N/A this is editorial only
* N/A
* Chrome: …
* Firefox: …
* Safari: …
* Deno (only for aborting and events): …
* Node.js (only for aborting and events): …
***
<a href="https://whatpr.org/dom/1100.html" title="Last updated on Aug 1, 2022, 1:02 PM UTC (52de3e5)">Preview</a> | <a …
=> [Editorial] Typo occurance -> occurrence in section's id

dom.bs
Following discussions in https://github.com/whatwg/html/issues/8340, the events index in the HTML spec will be restricted to event types that gets fired within the HTML spec. The `slotchange` event will be dropped as a result.
This turns the mention of the `slotchange` event into a proper event type definition, so that other specs (including the HTML spec) can reference it.
***
<a href="https://whatpr.org/dom/1115.html" title="Last updated on Oct 4, 2022, 3:52 PM UTC (1db0fe4)">Preview</a> | <a href="https://whatpr.org/dom/1115/fa3aea5...1db0fe4.html" title="Last updated on Oct 4, 2022, 3:52 PM UTC (1db0fe4)">Diff</a>
=> [meta] Define slotchange event

dom.bs
Clarify the usage of strictly split a string in the algorithm validate and extract defined for namespaces.
Fixes: https://github.com/whatwg/dom/issues/1134
***
<a href="https://whatpr.org/dom/1135.html" title="Last updated on Dec 13, 2022, 2:48 PM UTC (0242fae)">Preview</a> | <a href="https://whatpr.org/dom/1135/1aa6fb0...0242fae.html" title="Last updated on Dec 13, 2022, 2:48 PM UTC (0242fae)">Diff</a>
=> Editorial: clarify namespace validate and extract

dom.bs
And improve the algorithm "headers" at the same time by listing the argument types and default values.
***
<a href="https://whatpr.org/dom/1138.html" title="Last updated on Dec 15, 2022, 2:22 PM UTC (adb508f)">Preview</a> | <a href="https://whatpr.org/dom/1138/2f37778...adb508f.html" title="Last updated on Dec 15, 2022, 2:22 PM UTC (adb508f)">Diff</a>
=> Editorial: add some <div algorithm> wrappers

dom.bs
Closes #1149.
***
<a href="https://whatpr.org/dom/1151.html" title="Last updated on Feb 6, 2023, 7:33 AM UTC (0afea28)">Preview</a> | <a href="https://whatpr.org/dom/1151/8b0a622...0afea28.html" title="Last updated on Feb 6, 2023, 7:33 AM UTC (0afea28)">Diff</a>
=> Editorial: remove reference to time origin

dom.bs
The existing design had some leaks and was also different from implementations. In particular, assume you have two mutation observers and a change triggered the first one as well as a slot change. Then if in the reaction to the first one a further change triggers the second one it would run before the slot change per the existing specification, but that didn't match implementations and more importantly didn't allow for garbage collection.
Test: https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/slotchange-event.html#L540-L594.
Fixes #713. Fixes #1159. Closes #720.
***
<a href="https://whatpr.org/dom/1160.html" title="Last updated on Feb 17, 2023, 9:12 AM UTC (5d7c322)">Preview</a> | <a href="https://whatpr.org/dom/1160/0111a95...5d7c322.html" title="Last updated on Feb 17, …
=> Correct MutationObserver ownership story

dom.bs
* createNSResolver() returns the specified node.
* Element.lookupNamespaceURI() should handle 'xml' and 'xmlns' prefixes by default
Fixes #857
* Chromium: I'm positive
* Gecko: Already shipped
* WebKit: Positive; See https://github.com/whatwg/dom/issues/857#issuecomment-650694254
* https://github.com/web-platform-tests/wpt/pull/38636
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1418215
* Gecko: N/A (already shipped)
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=252716
* Deno (only for aborting and events): N/A
* Node.js (only for aborting and events): N/A
***
<a href="https://whatpr.org/dom/1165.html" title="Last updated on Feb 22, 2023, 4:10 PM UTC …
=> Update createNSResolver and lookupNamespaceURI()

dom.bs
Hi DOM folks,
I've got a working implementation of [AbortSignal.any()](https://github.com/shaseley/abort-signal-any) with tentative WPT tests, so I wanted to send out a draft spec for thoughts/consideration. It's probably not ready as-is because it would break other specs (see below), but this is how I thought the end state might look.
This adds IDL and algorithms for [AbortSignal.any()](https://github.com/shaseley/abort-signal-any).
Implementation details:
- This implements an optimization that puts all children on non-composite signals (i.e. those associated with a controller or timeout). This allows "intermediate" nodes (e.g. B in A follows B follows C) to be garbage collected if they are only being kept alive to propagate aborts.
- This removes the follow algorithm, so callsites will …
=> Add AbortSignal.any()

dom.bs
Split the attachShadow element list into a separate definition so that it can be referenced from the [EditContext spec](https://w3c.github.io/edit-context/#supported-elements).
See https://github.com/w3c/edit-context/issues/19.
***
<a href="https://whatpr.org/dom/1200.html" title="Last updated on May 22, 2023, 7:22 AM UTC (5ee87a7)">Preview</a> | <a href="https://whatpr.org/dom/1200/6c02df2...5ee87a7.html" title="Last updated on May 22, 2023, 7:22 AM UTC (5ee87a7)">Diff</a>
=> Editorial: Split attachShadow element list into separate definition

dom.bs
For https://github.com/whatwg/dom/issues/1194, so specs can use an AbortController and its signal rather than signaling abort directly on an AbortSignal.
***
<a href="https://whatpr.org/dom/1202.html" title="Last updated on May 25, 2023, 5:13 PM UTC (6110e11)">Preview</a> | <a href="https://whatpr.org/dom/1202/4b15d1f...6110e11.html" title="Last updated on May 25, 2023, 5:13 PM UTC (6110e11)">Diff</a>
=> Export AbortController's signal

dom.bs
Also add `<div algorithm>` wrappers to make this problem less likely to reoccur in this section.
Fixes #1203.
***
<a href="https://whatpr.org/dom/1204.html" title="Last updated on May 31, 2023, 10:39 AM UTC (68924eb)">Preview</a> | <a href="https://whatpr.org/dom/1204/8602242...68924eb.html" title="Last updated on May 31, 2023, 10:39 AM UTC (68924eb)">Diff</a>
=> Correct undefined variable in add an event listener

dom.bs
At least in chromium, synchronous internal listeners for attribute changes which are run as "attribute change steps" are run after the attribute is actually changed, not before.
This affects popover attribute related algorithms in HTML: https://github.com/whatwg/html/pull/9048#discussion_r1141122175
* Chromium
* Gecko
* WebKit
* The tests in this HTML PR effectively test this: https://github.com/whatwg/html/pull/9048
* Chromium: N/A
* Gecko: N/A
* WebKit: N/a
***
<a href="https://whatpr.org/dom/1176.html" title="Last updated on Jun 8, 2023, 3:38 PM UTC (40d679d)">Preview</a> | <a href="https://whatpr.org/dom/1176/90691ba...40d679d.html" title="Last updated on Jun 8, 2023, 3:38 PM UTC (40d679d)">Diff</a>
=> Handle attribute changes after changing attribute

dom.bs
This fixes an error just introduced in
3fb0aa62a96f0b3a8afb016ca95a805ccd3fc5b0; I happened to be reading the text today while working on something else.
cc @josepharhar
***
<a href="https://whatpr.org/dom/1209.html" title="Last updated on Jun 13, 2023, 2:05 AM UTC (55d4821)">Preview</a> | <a href="https://whatpr.org/dom/1209/3fb0aa6...55d4821.html" title="Last updated on Jun 13, 2023, 2:05 AM UTC (55d4821)">Diff</a>
=> Handle old value correctly when changing an attribute.

dom.bs
For https://github.com/whatwg/dom/issues/1194. Specs have been converted to use AbortController's signal abort (https://dontcallmedom.github.io/webdex/s.html).
***
<a href="https://whatpr.org/dom/1226.html" title="Last updated on Sep 26, 2023, 8:37 PM UTC (e96cebe)">Preview</a> | <a href="https://whatpr.org/dom/1226/2a24a27...e96cebe.html" title="Last updated on Sep 26, 2023, 8:37 PM UTC (e96cebe)">Diff</a>
=> Stop exporting AbortSignal's signal abort

dom.bs
The explainer for this feature is here: https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md
The issue discussion is here: https://github.com/whatwg/dom/issues/831
There is a corresponding [Pull Request](https://github.com/whatwg/html/pull/5465) for the HTML spec that goes along with this PR.
Note, due to some local branch issues, this is a duplicate of [PR 858](https://github.com/whatwg/dom/pull/858). Please see that PR for more history and review comments here. In particular, the last comment there [is from me](https://github.com/whatwg/dom/pull/858#issuecomment-668875565) - it is my belief that I've addressed all of the outstanding comments.
* I'm working to get this implemented in Chromium, tracking bug [here](https://crbug.com/1042130).
* Other implementers have at …
=> Add declarative Shadow DOM features

dom.bs
This adds a corresponding keyword to ShadowRootInit's clonable field.
* WebKit https://github.com/whatwg/dom/issues/1236#issuecomment-1830255479
* Blink https://github.com/whatwg/dom/issues/1236#issuecomment-1830335441
* Seems reasonable as a Gecko person myself
* https://github.com/web-platform-tests/wpt/pull/43602
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1510466
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1868428
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=266227
***
<a href="https://whatpr.org/dom/1237.html" title="Last updated on Dec 11, 2023, 4:31 PM UTC (fb58501)">Preview</a> | <a href="https://whatpr.org/dom/1237/ca756e0...fb58501.html" …
=> Add ShadowRoot clonable attribute

dom.bs
Also fix a typo that bikeshed was able to fix thanks to this.
* …
* …
* … 
* Chromium: …
* Gecko: …
* WebKit: …
* Deno (only for aborting and events): …
* Node.js (only for aborting and events): …
***
<a href="https://whatpr.org/dom/1240.html" title="Last updated on Dec 13, 2023, 3:13 PM UTC (5b7e0ea)">Preview</a> | <a href="https://whatpr.org/dom/1240/277983d...5b7e0ea.html" title="Last updated on Dec 13, 2023, 3:13 PM UTC (5b7e0ea)">Diff</a>
=> Editorial: mark up algorithms about Events

review-drafts/2023-12.bs
The [December 2023 Review Draft](https://dom.spec.whatwg.org/review-drafts/2023-12/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/dom/1242.html" title="Last updated on Dec 18, 2023, 12:02 PM UTC (1bea1c6)">Preview</a> | <a href="https://whatpr.org/dom/1242/03357df...1bea1c6.html" title="Last updated on Dec 18, 2023, 12:02 PM UTC (1bea1c6)">Diff</a>
=> Review Draft Publication: December 2023

dom.bs
This was an oversight in the spec, and this matches browser behavior. This makes a second call to `attachShadow()` throw.
This test already tests this condition: shadow-dom/declarative/declarative-shadow-dom-attachment.html
Closes https://github.com/whatwg/dom/issues/1234
@emilio
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 12, 2024, 7:32 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmfreed7 …
=> Reset declarative to false when calling attachShadow

dom.bs
Step 4.2.2. of [create a dependent abort signal](https://dom.spec.whatwg.org/#create-a-dependent-abort-signal) prevents duplicated signals in [source signals](https://dom.spec.whatwg.org/#abortsignal-source-signals) for example in the following snippet
```
const controller = new AbortController();
const signal = AbortSignal.any([ controller.signal, AbortSignal.any([controller.signal]) ]);
```
so maybe the same should hold for 
```
const signal2 = AbortSignal.any([ AbortSignal.any([controller.signal]), controller.signal ]);
const signal2 = AbortSignal.any([ controller.signal, controller.signal ]);
```
To my knowledge, duplicated signals in source signals should not have any impact due to step 1 of [signal abort](https://dom.spec.whatwg.org/#abortsignal-signal-abort) ensuring signals are …
=> Editorial: remove redundant contains check in AbortSignal.any()

dom.bs
Per the discussion at https://github.com/whatwg/dom/issues/1235, this PR changes the behavior when calling `attachShadow()` on a node with an existing declarative shadow root. Now, if the `mode` does not match between the arguments to `attachShadow()` and the existing root, throw an exception. Prior behavior was to silently return the declarative root as-is, with mismatched `mode`s.
See also, https://github.com/whatwg/html/pull/10069.
@emilio @annevk @rniwa
Closes https://github.com/whatwg/dom/issues/1235
* Chromium (me)
* WebKit [sounds supportive](https://github.com/whatwg/dom/issues/1235#issuecomment-1900422398)
* https://wpt.fyi/results/shadow-dom/declarative/declarative-shadow-dom-repeats.html
* Chromium: https://crbug.com/1379513
* Gecko: …
=> Enforce same parameters for attachShadow on declarative shadow root

dom.bs
See https://github.com/w3c/uievents/pull/362
* Already implemented in Chromium and WebKit
* Gecko is currently implementing.
* https://github.com/web-platform-tests/wpt/pull/44467
* Chromium: N/A
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=903746
* WebKit: N/A
* Deno (only for aborting and events): N/A
* Node.js (only for aborting and events): N/A
***
<a href="https://whatpr.org/dom/1254.html" title="Last updated on Feb 23, 2024, 11:47 AM UTC (fba814b)">Preview</a> | <a href="https://whatpr.org/dom/1254/73995b1...fba814b.html" title="Last updated on Feb 23, 2024, 11:47 AM UTC (fba814b)">Diff</a>
=> createEvent("textevent") creates a TextEvent

dom.bs
Similarly for 'in a document tree' and 'in a document'.
Fixes #1259.
(Omitted the PR template since this is a spec-only bug fix.)
***
<a href="https://whatpr.org/dom/1260.html" title="Last updated on Feb 27, 2024, 3:24 PM UTC (6e6406e)">Preview</a> | <a href="https://whatpr.org/dom/1260/73995b1...6e6406e.html" title="Last updated on Feb 27, 2024, 3:24 PM UTC (6e6406e)">Diff</a>
=> Define 'connected' for all nodes

dom.bs
Add `getHTML()` and the `serializable` concept for shadow roots. See https://github.com/whatwg/html/issues/8867#issuecomment-1856696628 for the rough consensus on how this should work, plus the few comments below that with modifications.
* Chromium
* [WebKit](https://github.com/whatwg/html/issues/8867#issuecomment-1910624523)
* 
* https://wpt.fyi/results/shadow-dom/declarative/gethtml.tentative.html
* Chromium: https://crbug.com/41490936
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1886630
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=271343
* https://github.com/mdn/content/issues/32731
See the corresponding HTML spec PR here: https://github.com/whatwg/html/pull/10139
***
<a href="https://whatpr.org/dom/1256.html" title="Last updated on Mar 20, 2024, 10:42 PM UTC …
=> Add serializable to ShadowRoot and "attach a shadow root"

dom.bs
This feeds into "Long Animation Frame" timing.
* Chromium (implemented)
* Gecko (https://github.com/mozilla/standards-positions/issues/929)
* See https://wpt.fyi/results/long-animation-frame/tentative/l
* Chromium: already implemented
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1348405
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=270913
***
<a href="https://whatpr.org/dom/1267.html" title="Last updated on Apr 15, 2024, 4:54 PM UTC (6902a5d)">Preview</a> | <a href="https://whatpr.org/dom/1267/68df785...6902a5d.html" title="Last updated on Apr 15, 2024, 4:54 PM UTC (6902a5d)">Diff</a>
=> Record timing info for event handling.

dom.bs
Fixes https://github.com/w3c/trusted-types/issues/438
* Chromium (already implemented)
* Gecko
* https://wpt.fyi/trusted-types already includes a number of tests for these changes.
* Chromium: Shipped
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1508286
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=270435
***
<a href="https://whatpr.org/dom/1258.html" title="Last updated on Apr 18, 2024, 2:14 PM UTC (6b615a7)">Preview</a> | <a href="https://whatpr.org/dom/1258/77cd75e...6b615a7.html" title="Last updated on Apr 18, 2024, 2:14 PM UTC (6b615a7)">Diff</a>
=> Integration with trusted types inside of node conversion

dom.bs
I was trying to check whether a switch statement was exhaustive and had to do a bit of mental juggling to get there. I thought I'd write out the results for future reference.
***
<a href="https://whatpr.org/dom/1279.html" title="Last updated on Apr 22, 2024, 2:55 AM UTC (9fae4af)">Preview</a> | <a href="https://whatpr.org/dom/1279/77cd75e...9fae4af.html" title="Last updated on Apr 22, 2024, 2:55 AM UTC (9fae4af)">Diff</a>
=> Editorial: explain the possible primary interfaces for nodes

dom.bs
This PR introduces a node's set of _post-connection steps_. For any given [#concept-node-insert](https://dom.spec.whatwg.org/#concept-node-insert) operation, these steps run for each inserted node synchronously _after_ all DOM insertions are complete. This PR is meant to supersede the similar https://github.com/whatwg/dom/pull/732.
The goal here is to separate the following:
1. Script-observable but not-script-executing insertion side effects
- This includes synchronously applying styles to the document, etc...
2. Script-executing insertion side effects
- This includes creating an iframe's document and [synchronously firing its load event](https://html.spec.whatwg.org/C#the-iframe-element:iframe-load-event-steps)
For any given call to …
=> Introduce DOM post-connection steps

dom.bs
This reverts commit 720a4fc20f0c7d9aa430ed418db92e474fdcf185.
These changes aren't needed given the current protection model used for script elements. See https://github.com/w3c/trusted-types/issues/537
* …
* WebKit (https://github.com/WebKit/WebKit/pull/31058)
* … 
* Chromium: …
* Gecko: …
* WebKit: …
* Deno (only for aborting and events): …
* Node.js (only for aborting and events): …
***
<a href="https://whatpr.org/dom/1299.html" title="Last updated on Jul 24, 2024, 1:36 PM UTC (561e804)">Preview</a> | <a href="https://whatpr.org/dom/1299/7c494e5...561e804.html" title="Last updated on Jul 24, 2024, 1:36 PM UTC (561e804)">Diff</a>
=> Revert "Trusted Types integration for "converting nodes into a node""

dom.bs
As this is a frequently made error, having it wrong in DOM does the community a disservice.
Fixes #1300.
***
<a href="https://whatpr.org/dom/1305.html" title="Last updated on Aug 13, 2024, 2:04 PM UTC (e1b39e0)">Preview</a> | <a href="https://whatpr.org/dom/1305/809bfa2...e1b39e0.html" title="Last updated on Aug 13, 2024, 2:04 PM UTC (e1b39e0)">Diff</a>
=> Correct doAmazingness() example

dom.bs
Since it was introduced in https://github.com/whatwg/dom/commit/43213eda4f80407950a897cc0b654ded5615809e we never invoked locating a namespace prefix correctly.
Fixes #1302.
(Skipping the template as this is an obvious bug fix with existing test coverage.)
***
<a href="https://whatpr.org/dom/1304.html" title="Last updated on Aug 13, 2024, 1:45 PM UTC (e8e6516)">Preview</a> | <a href="https://whatpr.org/dom/1304/809bfa2...e8e6516.html" title="Last updated on Aug 13, 2024, 1:45 PM UTC (e8e6516)">Diff</a>
=> Correct lookupPrefix() after fourteen years

dom.bs
It's necessary to specify which global these are reported to. This seems to be the event listener callback's realm's global in the event listener case, and the custom element constructor's realm, based on a combination of consistency with the related sites in HTML and browser behavior -- though browser behavior for custom elements isn't consistent in the (unusual) case of custom elements across realms.
Part of whatwg/html#10516.
* https://chromium-review.googlesource.com/c/chromium/src/+/5789341 (custom element upgrade)
* https://chromium-review.googlesource.com/c/chromium/src/+/5784046 (event dispatch)
* Chromium: https://crbug.com/359909516
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1378265
* WebKit: n/a (WPTs seem to pass, except for customized built-in elements, which …
=> Update to use new "report an exception" algorithm in HTML

dom.bs
The assert in 4.2.1 of "create a dependent abort signal" fails when creating a dependent signal while dispatching abort events or running abort algorithms if abort had not yet been propagated to one of the sources.
This fix splits "signal abort" into two phases: first, set the abort reason on the signal being aborted and all of its unaborted dependents; next, run the abort algorithms and dispatch events for the signal and those same dependents. Note that:
1. Dependent signals do not themselves have dependent signals, which means it's unnecessary to recursively call "signal abort"
2. This approach retains the existing event dispatch order, while ensuring the abort state is synced before any JS runs
This fixes #1293.
---
* Chromium
* WebKit
* Chromium: …
=> Mark dependent abort signals as aborted before firing events

dom.bs
If you have two once listeners and the first one dispatches a second event that invokes both listeners, the second listener would be invoked twice as it had already been cloned before it got removed. As such setting its removed field is important after all.
Fixes #1323.
* Already implemented.
* Already tested, see issue.
* N/A.
***
<a href="https://whatpr.org/dom/1324.html" title="Last updated on Nov 18, 2024, 9:40 AM UTC (1ff8299)">Preview</a> | <a href="https://whatpr.org/dom/1324/7cacda2...1ff8299.html" title="Last updated on Nov 18, 2024, 9:40 AM UTC (1ff8299)">Diff</a>
=> Correct once handling for "nested" events

dom.bs
This is slightly cleaner and less confusing (to me anyway).
***
<a href="https://whatpr.org/dom/1325.html" title="Last updated on Nov 18, 2024, 11:00 AM UTC (08c84c0)">Preview</a> | <a href="https://whatpr.org/dom/1325/c2d5aa3...08c84c0.html" title="Last updated on Nov 18, 2024, 11:00 AM UTC (08c84c0)">Diff</a>
=> Editorial: break from the inner invoke loop rather than returning

dom.bs
This PR is a follow-up that was identified from discussion in https://github.com/whatwg/dom/pull/1307.
***
<a href="https://whatpr.org/dom/1330.html" title="Last updated on Dec 12, 2024, 2:03 PM UTC (d7fb531)">Preview</a> | <a href="https://whatpr.org/dom/1330/7c494e5...d7fb531.html" title="Last updated on Dec 12, 2024, 2:03 PM UTC (d7fb531)">Diff</a>
=> Editorial: unconjugate "pre-insertion" and "pre-removing"

dom.bs
***
<a href="https://whatpr.org/dom/1331.html" title="Last updated on Dec 12, 2024, 12:57 PM UTC (4456b0e)">Preview</a> | <a href="https://whatpr.org/dom/1331/bb30d16...4456b0e.html" title="Last updated on Dec 12, 2024, 12:57 PM UTC (4456b0e)">Diff</a>
=> Editorial: cleanup "create an element"

dom.bs
Also no need for a trailing "then" when there are nested steps.
***
<a href="https://whatpr.org/dom/1333.html" title="Last updated on Dec 12, 2024, 3:46 PM UTC (46470fc)">Preview</a> | <a href="https://whatpr.org/dom/1333/37fb987...46470fc.html" title="Last updated on Dec 12, 2024, 3:46 PM UTC (46470fc)">Diff</a>
=> Editorial: modernize "enqueue a custom element callback reaction"

dom.bs
This is needed for #1334.
***
<a href="https://whatpr.org/dom/1337.html" title="Last updated on Dec 16, 2024, 10:36 AM UTC (ddcd39c)">Preview</a> | <a href="https://whatpr.org/dom/1337/e17e509...ddcd39c.html" title="Last updated on Dec 16, 2024, 10:36 AM UTC (ddcd39c)">Diff</a>
=> Meta: give all document references an explicit for attribute

dom.bs
Also clean up "for each" wording while here.
Fixes #1344.
***
<a href="https://whatpr.org/dom/1347.html" title="Last updated on Jan 6, 2025, 1:37 PM UTC (20ee860)">Preview</a> | <a href="https://whatpr.org/dom/1347/7cd51e7...20ee860.html" title="Last updated on Jan 6, 2025, 1:37 PM UTC (20ee860)">Diff</a>
=> Editorial: initialize clearTargets in event dispatch correctly

dom.bs
Also stop exporting "find a slot" as it's not used elsewhere.
Fixes #1349.
***
<a href="https://whatpr.org/dom/1350.html" title="Last updated on Jan 20, 2025, 9:32 AM UTC (7261e45)">Preview</a> | <a href="https://whatpr.org/dom/1350/369654b...7261e45.html" title="Last updated on Jan 20, 2025, 9:32 AM UTC (7261e45)">Diff</a>
=> Editorial: modernize the slot algorithms

dom.bs
Closes #1343.
***
<a href="https://whatpr.org/dom/1358.html" title="Last updated on Feb 10, 2025, 1:32 PM UTC (3f20fa9)">Preview</a> | <a href="https://whatpr.org/dom/1358/e6bb175...3f20fa9.html" title="Last updated on Feb 10, 2025, 1:32 PM UTC (3f20fa9)">Diff</a>
=> Clarify composedPath() method steps with an assert

dom.bs
When an attribute is appended to an element or is replacing an existing attribute, we need to ensure that its node document remains accurate.
Fixes #1359.
***
<a href="https://whatpr.org/dom/1360.html" title="Last updated on Feb 20, 2025, 4:19 PM UTC (1a6322c)">Preview</a> | <a href="https://whatpr.org/dom/1360/cbf4c0d...1a6322c.html" title="Last updated on Feb 20, 2025, 4:19 PM UTC (1a6322c)">Diff</a>
=> Update an attribute's node document

dom.bs
**Please do not comment directly on this PR unless asked**. It's a big change and we want to keep it manageable. Use #1339 instead.
HTML PR: https://github.com/whatwg/html/pull/10869.
Tests: https://github.com/web-platform-tests/wpt/pull/50790.
* WebKit
* Gecko
* Chromium
* https://github.com/web-platform-tests/wpt/pull/50790
* https://github.com/web-platform-tests/wpt/pull/50860
* https://github.com/web-platform-tests/wpt/pull/51953
* Chromium: https://issues.chromium.org/issues/399124619
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1874414
* WebKit: N/A
***
<a href="https://whatpr.org/dom/1341.html" title="Last updated on Apr 14, 2025, 8:29 AM UTC (a77c2b8)">Preview</a> | <a …
=> Add Scoped Custom Element Registries

dom.bs
Stop using XML grammar productions for validating element, attribute, and doctype names. These were overly-restrictive, as it is possible to create nodes with names that don't match those productions using the HTML parser. After this change, each construct has its own custom name validation algorithm.
The only remaining dependency on XML naming rules is for processing instructions, which are uncommon and cannot be created with the HTML parser anyway.
Closes #769. Closes #849. Closes #1373.
* Gecko
* Chromium
* https://github.com/web-platform-tests/wpt/pull/38503
* https://chromium-review.googlesource.com/c/chromium/src/+/6570951
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1334640
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1773312
* Safari: …
=> Allow more characters when creating various nodes

review-drafts/2025-06.bs
The [June 2025 Review Draft](https://dom.spec.whatwg.org/review-drafts/2025-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/dom/1381.html" title="Last updated on Jun 16, 2025, 7:33 AM UTC (8908c69)">Preview</a> | <a href="https://whatpr.org/dom/1381/e67d5fe...8908c69.html" title="Last updated on Jun 16, 2025, 7:33 AM UTC (8908c69)">Diff</a>
=> Review Draft Publication: June 2025
